let previousFocus;
export const $ = (selector, root = document) => root.querySelector(selector);
export const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
export function toast(message, type = 'info') { const el = $('.toast'); if (!el) return; el.textContent = message; el.dataset.type = type; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 4200); }
export function openModal(el) { if (!el) return; previousFocus = document.activeElement; el.hidden = false; document.body.classList.add('modal-open'); requestAnimationFrame(() => $('button,input,select,textarea', el)?.focus()); }
export function closeModal(el) { if (!el) return; el.hidden = true; if (!$$('.platform-modal:not([hidden]),.settings-panel:not([hidden])').length) document.body.classList.remove('modal-open'); previousFocus?.focus?.(); }
export function setBusy(form, busy) { const btn = $('[type="submit"]', form); if (!btn) return; btn.disabled = busy; btn.dataset.label ||= btn.textContent; btn.textContent = busy ? 'Carregando…' : btn.dataset.label; }
export function renderEmpty(container, text) { container.replaceChildren(Object.assign(document.createElement('p'), { className: 'empty-state', textContent: text })); }
export function field(label, name, type='text', required=true) { const l=document.createElement('label'); l.textContent=label; const i=document.createElement(type==='textarea'?'textarea':'input'); i.name=name; if(type!=='textarea') i.type=type; i.required=required; l.append(i); return l; }
export function installDialogControls() { document.addEventListener('click', e => { const close=e.target.closest('[data-close-platform]'); if(close) closeModal(close.closest('.platform-modal')); }); document.addEventListener('keydown', e => { if(e.key==='Escape') { const open=$$('.platform-modal:not([hidden]),.settings-panel:not([hidden])').pop(); if(open && open.dataset.requiredModal !== 'true') closeModal(open); } if(e.key==='Tab'){ const modal=$$('.platform-modal:not([hidden])').pop(); if(!modal)return; const f=$$('button:not(:disabled),input,select,textarea,a[href]',modal); if(!f.length)return; if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()} else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()} } }); }
