let previousFocus;
export const $ = (selector, root = document) => root.querySelector(selector);
export const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
export function toast(message, type = 'info') { const el = $('.toast'); if (!el) return; el.textContent = message; el.dataset.type = type; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 4200); }
export function trapModalFocus(event, modal) { const focusable=$$('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]',modal); if(!focusable.length)return; const first=focusable[0],last=focusable.at(-1); if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()} }
export function restoreModalFocus() { const target=previousFocus; previousFocus=null; target?.focus?.(); }
export function openModal(el) { if (!el) return false; previousFocus = document.activeElement; el.hidden = false; el.classList.add('is-open'); el.setAttribute('aria-hidden','false'); document.body.classList.add('modal-open'); requestAnimationFrame(() => $('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]', el)?.focus()); return true; }
export function closeModal(el) { if (!el || el.hidden) return false; el.hidden = true; el.classList.remove('is-open'); el.setAttribute('aria-hidden','true'); if (!$$('.platform-modal:not([hidden]),.settings-panel:not([hidden])').length) document.body.classList.remove('modal-open'); restoreModalFocus(); return true; }
export function setBusy(form, busy) { const btn = $('[type="submit"]', form); if (!btn) return; btn.disabled = busy; btn.dataset.label ||= btn.textContent; btn.textContent = busy ? 'Carregando…' : btn.dataset.label; }
export function renderEmpty(container, text) { container.replaceChildren(Object.assign(document.createElement('p'), { className: 'empty-state', textContent: text })); }
export function field(label, name, type='text', required=true) { const l=document.createElement('label'); l.textContent=label; const i=document.createElement(type==='textarea'?'textarea':'input'); i.name=name; if(type!=='textarea') i.type=type; i.required=required; l.append(i); return l; }
export function installDialogControls() { if(installDialogControls.installed)return; installDialogControls.installed=true; document.addEventListener('click', e => { const close=e.target.closest('[data-close-platform]'); if(close) closeModal(close.closest('.platform-modal')); }); document.addEventListener('keydown', e => { const open=$$('.platform-modal:not([hidden]),.settings-panel:not([hidden])').pop(); if(e.key==='Escape'&&open&&open.dataset.requiredModal!=='true')closeModal(open); else if(e.key==='Tab'&&open?.classList.contains('platform-modal'))trapModalFocus(e,open); }); }
