import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import worker from '../worker.js';
const root=new URL('../',import.meta.url),types={'.html':'text/html','.js':'text/javascript','.css':'text/css'};
async function assetFetch(request){const pathname=new URL(request.url).pathname,file=pathname==='/'?'index.html':pathname.slice(1);try{return new Response(await readFile(new URL(file,root)),{headers:{'Content-Type':types[file.slice(file.lastIndexOf('.'))]||'application/octet-stream'}})}catch{return new Response('Not found',{status:404})}}
const env={ASSETS:{fetch:assetFetch}},request=path=>worker.fetch(new Request(`https://local.test${path}`,{headers:{Accept:'text/html'}}),env);
test('Home contém apenas link e não referencia módulos pesados',async()=>{const html=await request('/').then(r=>r.text());assert.match(html,/href="\/Emuladores\/"/);assert.doesNotMatch(html,/Emuladores\/(?:PS1|GBC|GBA|cores)|EmulatorJS|\.wasm|emulators\.js/);});
test('área central usa somente registry e aponta às pastas dos consoles',async()=>{const [html,source]=await Promise.all([request('/Emuladores/').then(r=>r.text()),readFile(new URL('../Emuladores/emulators.js',import.meta.url),'utf8')]);assert.match(html,/emulators\.js/);assert.match(source,/emulator-registry\.js/);assert.doesNotMatch(source,/loading-manager|EmulatorJS|\.wasm/);});
for(const [id,folder] of [['ps1','PS1'],['gbc','GBC'],['gba','GBA']])test(`${id} possui biblioteca e player em rota limpa`,async()=>{assert.equal((await request(`/Emuladores/${folder}/`)).status,200);const player=await request(`/Emuladores/${folder}/player?game=abc`);assert.equal(player.status,200);assert.match(await player.text(),new RegExp(`${id}-player\\.js`));});
test('URLs antigas redirecionam uma vez às novas rotas',async()=>{for(const [old,target] of [['/gbc-player','/Emuladores/GBC/player'],['/gba-player.html','/Emuladores/GBA/player'],['/ps1-player','/Emuladores/PS1/player'],['/emulators','/Emuladores/']]){const response=await request(`${old}?game=abc`);assert.equal(response.status,308);const location=new URL(response.headers.get('location'));assert.equal(location.pathname,target);assert.equal((await request(`${location.pathname}${location.search}`)).status,200);}});
test('registry é metadata-only e declara os três cores',async()=>{const source=await readFile(new URL('../Emuladores/emulator-registry.js',import.meta.url),'utf8');for(const value of ["id:'ps1'","id:'gbc'","id:'gba'","engine:'pcsx_rearmed'","engine:'gambatte'","engine:'mGBA'"])assert.match(source,new RegExp(value));assert.doesNotMatch(source,/^import /m);});
