import test from 'node:test';
import assert from 'node:assert/strict';
import {EmulatorBootDiagnostics,EmulatorLoadingManager,LOADING_PHASES,INITIALIZATION_STEPS} from '../emulator-loading-manager.js';
const root={querySelector(){return null;}};
test('fases públicas e etapas técnicas são centralizadas',()=>{for(const phase of ['preparing','network','downloading','download_complete','loading_runtime','loading_core','creating_canvas','mounting_content','starting_core','waiting_first_frame','running','error'])assert.ok(LOADING_PHASES.includes(phase));assert.equal(INITIALIZATION_STEPS.core_loaded.progress,55);});
test('total é monotônico e só chega a 100 no primeiro frame',()=>{const loading=new EmulatorLoadingManager({profile:'gbc',root});loading.setPhase('network').setDownloadProgress(100);const downloaded=loading.snapshot().totalProgress;loading.completeStep('core_loaded');const core=loading.snapshot().totalProgress;assert.ok(core>=downloaded);assert.ok(core<100);loading.completeStep('waiting_first_frame');assert.ok(loading.snapshot().totalProgress<100);loading.markFirstFrame();assert.equal(loading.snapshot().totalProgress,100);});
test('progresso de inicialização só avança ao concluir eventos reais',()=>{const loading=new EmulatorLoadingManager({root});loading.completeStep('loader_loaded');assert.equal(loading.snapshot().initializationProgress,25);loading.completeStep('core_loaded');assert.equal(loading.snapshot().initializationProgress,55);});

function fakeTime(){let id=0;const jobs=new Map();const add=(kind,fn)=>{jobs.set(++id,{kind,fn});return id};return {setTimeout:fn=>add('timeout',fn),clearTimeout:key=>jobs.delete(key),setInterval:fn=>add('interval',fn),clearInterval:key=>jobs.delete(key),run(kind){for(const [key,job] of [...jobs])if(job.kind===kind){if(kind==='timeout')jobs.delete(key);job.fn();}}};}
test('diagnóstico converte falha/timeout de runtime, WASM 404 e core em erro específico',()=>{for(const phase of ['runtime_loading','core_loading']){const time=fakeTime(),errors=[],loading=new EmulatorLoadingManager({root}),boot=new EmulatorBootDiagnostics({system:'gbc',loading,time,onError:error=>errors.push(error)});boot.enter(phase,{timeout:1});time.run('timeout');assert.equal(loading.phase,'error');assert.equal(errors[0].code,phase);assert.match(errors[0].detail,/Etapa:/);}});
test('ROM válida avança por core, canvas, conteúdo e primeiro frame reais',()=>{const original=globalThis.EJS_emulator,canvas={width:160,height:144},time=fakeTime(),loading=new EmulatorLoadingManager({root}),boot=new EmulatorBootDiagnostics({system:'gbc',container:{querySelector:()=>canvas},loading,time});globalThis.EJS_emulator={};boot.watchRuntime();time.run('interval');assert.ok(loading.completed.has('core_loaded'));assert.ok(loading.completed.has('canvas_created'));boot.mounted().waitingFirstFrame();loading.completeStep('waiting_first_frame');boot.running();loading.markFirstFrame();assert.equal(loading.phase,'running');globalThis.EJS_emulator=original;});
test('WebGL/canvas ausente e first frame ausente nunca ficam em loading infinito',()=>{const original=globalThis.EJS_emulator,time=fakeTime(),errors=[],loading=new EmulatorLoadingManager({root}),boot=new EmulatorBootDiagnostics({system:'gba',container:{querySelector:()=>null},loading,time,onError:error=>errors.push(error)});globalThis.EJS_emulator={};boot.watchRuntime();time.run('interval');assert.ok(loading.completed.has('core_loaded'));time.run('timeout');assert.equal(loading.phase,'error');assert.equal(errors.at(-1).code,'canvas_creation');globalThis.EJS_emulator=original;});
