import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
test('perfil edita somente os quatro campos permitidos pela sessão',async()=>{const worker=await read('worker.js');assert.match(worker,/allowed=new Set\(\['displayName','avatar','bio','isPublic'\]\)/);assert.match(worker,/WHERE id=\?"?\)\.bind\(displayName,payload\.avatar,bio,payload\.isPublic\?1:0,user\.id\)/);assert.doesNotMatch(worker,/payload\.user_?[Ii]d/);});
test('perfil oferece identidade real e somente avatares internos',async()=>{const [html,js,worker]=await Promise.all([read('profile.html'),read('profile.js'),read('worker.js')]);for(const value of ['displayName','avatar','bio','isPublic'])assert.match(html,new RegExp(`name="${value}"`));assert.doesNotMatch(html,/type="file"|Preferências sincronizadas|name="theme"/);assert.doesNotMatch(js,/compressAvatar|\/api\/profile\/avatar/);assert.doesNotMatch(worker,/GitHubAvatarStorage|avatarApi/);assert.match(js,/user\.displayName\|\|user\.username/);for(const avatar of ['mago','hacker','jogador','gamer']){assert.match(html,new RegExp(`value=\"${avatar}\"`));assert.match(js,new RegExp(`/assets/profile/avatars/${avatar}\\.svg`));assert.match(worker,new RegExp(`'${avatar}'`));}});

test('privacidade pública é imposta no backend e ranking usa tempo acumulado',async()=>{const [html,js,worker]=await Promise.all([read('profile.html'),read('profile.js'),read('worker.js')]);assert.match(worker,/\/api\/profile\/public\//);assert.match(worker,/status='accepted'/);assert.match(worker,/Este perfil é privado/);assert.match(worker,/ORDER BY s\.total_seconds DESC/);assert.match(html,/Jogos com mais tempo/);assert.match(js,/sort\(\(a,b\)=>Number\(b\.totalSeconds\)-Number\(a\.totalSeconds\)\)\.slice\(0,5\)/);});

test('perfil evita auth/me concorrente, limita bio e envia cookie explicitamente',async()=>{const [html,js,worker]=await Promise.all([read('profile.html'),read('profile.js'),read('worker.js')]);assert.doesNotMatch(js,/call\('\/api\/auth\/me'/);assert.match(js,/credentials:'include'/);assert.match(js,/cache:'no-store'/);assert.match(html,/name="bio" maxlength="200"/);assert.match(worker,/bio\.length>200/);});

test('bloco institucional fica entre header e main sem footer antigo nem navegação duplicada',async()=>{const html=await read('index.html');const block=html.match(/<aside class="institutional-strip"[\s\S]*?<\/aside>/)?.[0]||'';assert.ok(html.indexOf('institutional-strip')>html.indexOf('</header>'));assert.ok(html.indexOf('institutional-strip')<html.indexOf('<main id="main-content">'));assert.doesNotMatch(html,/<footer class="site-footer"/);assert.doesNotMatch(block,/data-view-link|Home|Biblioteca|Emuladores|Perfil/);});
