import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8'),router=fs.readFileSync('app-router.js','utf8'),worker=fs.readFileSync('worker.js','utf8'),manifest=JSON.parse(fs.readFileSync('manifest.json','utf8')),migration=fs.readFileSync('migrations/0007_user_game_preferences_and_trophies.sql','utf8');
test('navegação principal tem as quatro áreas SPA na ordem esperada',()=>{assert.deepEqual([...new Set([...html.matchAll(/data-view-link="([^"]+)/g)].map(m=>m[1]))],['workspace','emulators','utilities','profile']);assert.match(router,/VIEW_ORDER = \['workspace', 'emulators', 'utilities', 'profile'\]/)});
test('rota raiz resolve workspace sem reescrever a URL',()=>{assert.match(router,/const DEFAULT_VIEW = 'workspace'/);assert.match(router,/value && views\.has\(value\) \? value : DEFAULT_VIEW/);assert.match(router,/history\.replaceState\(\{ view: activeView \}, '', location\.href\)/);assert.doesNotMatch(router,/location\.pathname\}\?view=\$\{activeView\}/)});
test('router só inicia uma view depois da autenticação',()=>{assert.match(router,/addEventListener\('plumpgames:authenticated', startRouter/);assert.match(router,/initializeView\(views\.get\(activeView\)\)/)});
test('atalho PWA abre a raiz limpa',()=>{assert.equal(manifest.start_url,'/');assert.equal(manifest.scope,'/')});
test('workspace consulta apenas recentes e favoritos universais',()=>{assert.match(worker,/\/api\/player\/workspace/);assert.match(worker,/ORDER BY s\.last_played_at DESC LIMIT 3/);assert.match(worker,/\/api\/player\/preference/)});
test('migration é aditiva e preserva autenticação',()=>{assert.match(migration,/CREATE TABLE IF NOT EXISTS user_game_preferences/);assert.match(migration,/CREATE TABLE IF NOT EXISTS user_trophies/);assert.doesNotMatch(migration,/^(?:DROP|DELETE|ALTER TABLE)/im)});
test('players usam runtime EmulatorJS local sem CDN',()=>{for(const f of ['Emuladores/PS1/ps1-player.js','Emuladores/GBC/gbc-player.js','Emuladores/GBA/gba-player.js']){const source=fs.readFileSync(f,'utf8');assert.match(source,/\/Emuladores\/vendor\/emulatorjs\/data\//);assert.doesNotMatch(source,/cdn\.emulatorjs/)}});
