const DATA='https://cdn.emulatorjs.org/stable/data/', $=selector=>document.querySelector(selector), gameId=new URLSearchParams(location.search).get('game')||'', shell=$('#gbc-player-shell');
let game, controller, objectUrl, loader, started=false, bootReady=false;
const mobile=()=>matchMedia('(pointer:coarse)').matches&&navigator.maxTouchPoints>0;
function phase(text,percent){$('#loading-phase').textContent=text;if(percent!=null){$('#loading-percent').textContent=`${percent}%`;$('#progress-bar').style.width=`${percent}%`;}}
function fail(error){$('#loading').hidden=true;$('#error').hidden=false;$('#error p').textContent=error.message||String(error);}
async function fullscreen(){try{if(!document.fullscreenElement)await shell.requestFullscreen();try{await screen.orientation?.lock?.('landscape');}catch{}return true;}catch{return false;}}
function play(){if(started)return;started=true;$('#fullscreen-prompt').hidden=true;phase('Iniciando jogo...',100);try{window.EJS_emulator?.play?.();}catch{}setTimeout(()=>{if(!$('#loading').hidden)fail(new Error('O jogo não confirmou o início. Tente novamente.'));},15000);}
async function gate(){bootReady=true;if(!mobile()){play();return;}try{window.EJS_emulator?.pause?.();}catch{}if(await fullscreen())play();else $('#fullscreen-prompt').hidden=false;}
async function download(url,totalHint){const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw new Error('Não foi possível carregar a ROM.');const total=Number(response.headers.get('Content-Length'))||totalHint||0;if(!response.body){const blob=await response.blob();phase('Carregando jogo...',100);return blob;}const reader=response.body.getReader(),chunks=[];let loaded=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;phase('Carregando jogo...',total?Math.floor(loaded/total*100):0);}return new Blob(chunks,{type:'application/octet-stream'});}
async function start(){controller?.abort();controller=new AbortController();started=bootReady=false;$('#error').hidden=true;$('#loading').hidden=false;phase('Preparando...',0);try{const libraryResponse=await fetch('/api/emulators/gbc/games',{signal:controller.signal}),library=await libraryResponse.json();if(!libraryResponse.ok)throw new Error(library.error);game=library.games.find(item=>item.id===gameId);if(!game)throw new Error('Jogo GBC não encontrado.');$('#game-name').textContent=$('#loading-game').textContent=game.name;document.title=`${game.name} — PlumpGames`;const blob=await download(`/api/emulators/gbc/file/${encodeURIComponent(game.bootKey)}`,game.size);if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);phase('Inicializando emulador...',100);
Object.assign(window,{EJS_player:'#gbc-emulator',EJS_core:'gb',EJS_gameUrl:objectUrl,EJS_pathtodata:DATA,EJS_startOnLoaded:false,EJS_gameName:game.name,EJS_threads:false,EJS_VirtualGamepadSettings:{}});
window.EJS_onLoadState=()=>phase('Inicializando emulador...',100);window.EJS_onGameStart=()=>gate();window.EJS_onAudioStart=()=>{$('#loading').hidden=true;};
loader?.remove();loader=document.createElement('script');loader.src=`${DATA}loader.js`;loader.onerror=()=>fail(new Error('Falha ao carregar o core Gambatte do EmulatorJS.'));document.head.append(loader);
}catch(error){if(error.name!=='AbortError')fail(error);}}
$('#fullscreen-prompt').onclick=async()=>{await fullscreen();play();};$('#fullscreen').onclick=()=>fullscreen();$('#restart').onclick=start;$('#retry').onclick=start;$('#settings-toggle').onclick=()=>{const open=$('#settings').hidden;$('#settings').hidden=!open;$('#settings-backdrop').hidden=!open;$('#settings-toggle').setAttribute('aria-expanded',open);};$('#settings-close').onclick=$('#settings-backdrop').onclick=()=>{$('#settings').hidden=true;$('#settings-backdrop').hidden=true;};addEventListener('pagehide',()=>{controller?.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);});start();
