import {formatPlaytime,tierFor} from './player-profile.js';
const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));let games=[];
function renderSummary(summary={}){$('#summary').innerHTML=`<article><strong>${formatPlaytime(summary.totalSeconds)}</strong><span>Tempo total</span></article><article><strong>${summary.gamesPlayed||0}</strong><span>Jogos jogados</span></article><article><strong>${escape(summary.mostPlayed?.title||'—')}</strong><span>Mais jogado</span></article><article><strong>${escape(summary.lastPlayed?.title||'—')}</strong><span>Último jogo</span></article>`;}
function rank(tiers=false){return games.map((game,index)=>`<div class="rank-row"><b>${tiers?tierFor(index,games.length)||'—':index+1}</b><span>${escape(game.title)}</span><strong>${formatPlaytime(game.totalSeconds)}</strong></div>`).join('')||'<p class="muted">Jogue para começar seu ranking.</p>';}
function renderGames(){$('#profile-games').innerHTML=games.map(game=>`<article class="game-row">${game.cover?`<img class="game-cover" src="${escape(game.cover)}" alt="">`:'<div class="game-cover"></div>'}<div><strong>${escape(game.title)}</strong><br><small class="muted">${escape(game.system)}</small></div><span>${formatPlaytime(game.totalSeconds)}</span><span class="muted">${game.sessions} ${game.sessions===1?'sessão':'sessões'} · ${new Date(game.lastPlayedAt).toLocaleDateString('pt-BR')}</span></article>`).join('')||'<p class="muted">Nenhum jogo registrado ainda.</p>';}
async function call(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});const data=await response.json().catch(()=>({}));if(response.status===401){location.href='/?login=required';throw new Error('Sessão expirada');}if(!response.ok)throw new Error(data.error||'Falha na operação');return data;}
async function load(){try{const data=await call('/api/profile/stats');games=data.games||[];$('#profile-username').textContent=data.user.username;renderSummary(data.summary);$('#ranking').innerHTML=rank();renderGames();$('#profile-status').textContent=`Conta de ${data.user.username}`;}catch(error){$('#profile-status').textContent=error.message;}}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{$('[data-mode].active').classList.remove('active');button.classList.add('active');$('#ranking').innerHTML=rank(button.dataset.mode==='tiers');});
$('#export-history').onclick=async()=>{const blob=new Blob([JSON.stringify(await call('/api/player/export'),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plumpgames-historico.json';a.click();URL.revokeObjectURL(a.href);};
$('#delete-history').onclick=async()=>{if(confirm('Apagar definitivamente seu histórico de jogos?')){await call('/api/player/history',{method:'DELETE',headers:{'X-PlumpGames-Request':'same-origin'}});location.reload();}};
$('#logout').onclick=async()=>{await call('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json','X-PlumpGames-Request':'same-origin'},body:'{}'});location.href='/';};
$('#change-password').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await call('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json','X-PlumpGames-Request':'same-origin'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});event.target.reset();$('#profile-status').textContent='Senha alterada com sucesso.';}catch(error){$('#profile-status').textContent=error.message;}finally{button.disabled=false;}};
load();
