import {playerProfile,formatPlaytime,tierFor} from './player-profile.js';

const $=s=>document.querySelector(s);let games=[];const escape=value=>{const el=document.createElement('span');el.textContent=String(value??'');return el.innerHTML;};
function summaryCard(label,value){return `<article class="stat-card"><small>${label}</small><strong>${escape(value)}</strong></article>`;}
function renderSummary(summary){$('#summary').innerHTML=summaryCard('Tempo total',formatPlaytime(summary.totalSeconds))+summaryCard('Jogos diferentes',summary.gamesPlayed)+summaryCard('Sessões',summary.totalSessions)+summaryCard('Mais jogado',summary.mostPlayed?.title||'—')+summaryCard('Último jogo',summary.lastPlayed?.title||'—');}
function rank(){return games.map((game,index)=>`<div class="rank-row"><b class="rank-number">${index+1}</b><span>${escape(game.title)} <small class="muted">${escape(game.system)}</small></span><strong>${formatPlaytime(game.totalSeconds)}</strong></div>`).join('')||'<p class="muted">Jogue algo para iniciar seu ranking.</p>';}
function tiers(){if(games.length<3)return rank();const buckets={S:[],A:[],B:[],C:[],D:[]};games.forEach((game,index)=>buckets[tierFor(index,games.length)].push(game));return Object.entries(buckets).map(([tier,items])=>`<div class="tier"><b>${tier}</b><div>${items.map(g=>`<span>${escape(g.title)} · ${formatPlaytime(g.totalSeconds)}</span>`).join('')||'<small class="muted">—</small>'}</div></div>`).join('');}
function renderGames(){ $('#profile-games').innerHTML=games.map(game=>`<article class="game-row">${game.cover?`<img class="game-cover" src="${escape(game.cover)}" alt="">`:'<div class="game-cover"></div>'}<div><strong>${escape(game.title)}</strong><br><small class="muted">${escape(game.system)}</small></div><span>${formatPlaytime(game.totalSeconds)}</span><span class="muted">${game.sessions} ${game.sessions===1?'sessão':'sessões'} · ${new Date(game.lastPlayedAt).toLocaleDateString('pt-BR')}</span></article>`).join('')||'<p class="muted">Nenhum jogo registrado ainda.</p>';}
const playerHeaders=()=>({'X-PlumpGames-Player':playerProfile.get().guestPlayerId});
async function load(){try{const response=await fetch('/api/player/stats',{credentials:'same-origin',headers:playerHeaders()});if(!response.ok)throw new Error();const data=await response.json();games=data.games||[];renderSummary(data.summary);$('#ranking').innerHTML=rank();renderGames();$('#profile-status').textContent=`Perfil local ${playerProfile.get().guestPlayerId.slice(0,8)}…`; }catch{$('#profile-status').textContent='As estatísticas estão indisponíveis agora. Seus jogos continuam funcionando normalmente.';}}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===button));$('#ranking').innerHTML=button.dataset.mode==='tiers'?tiers():rank();}));
$('#export-history').onclick=async()=>{const response=await fetch('/api/player/export',{headers:playerHeaders()});if(!response.ok)return;const blob=new Blob([JSON.stringify(await response.json(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plumpgames-historico.json';a.click();URL.revokeObjectURL(a.href);};
$('#delete-history').onclick=async()=>{if(!confirm('Apagar definitivamente todo o seu histórico deste perfil?'))return;const response=await fetch('/api/player/history',{method:'DELETE',headers:playerHeaders()});if(response.ok){playerProfile.reset();location.reload();}};
load();
