import {formatPlaytime} from './player-profile.js';
const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const avatarPaths={mago:'/assets/profile/avatars/mago.svg',hacker:'/assets/profile/avatars/hacker.svg',jogador:'/assets/profile/avatars/jogador.svg',gamer:'/assets/profile/avatars/gamer.svg'};let games=[],profile,trophies=[],trophyRegistry=[];
async function call(path,options={}){const response=await fetch(path,{credentials:'include',cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(response.status===401){location.href='/?login=required';throw new Error('Sessão expirada');}if(!response.ok)throw new Error(data.error||'Falha na operação');return data;}
const writeOptions={headers:{'Content-Type':'application/json','X-PlumpGames-Request':'same-origin'}};
function avatarMarkup(user){const avatar=String(user.avatar||'');const path=avatarPaths[avatar]||avatarPaths.gamer;return `<img src="${path}" alt="" loading="lazy" decoding="async">`;}
function renderIdentity(user){profile=user;$('#profile-display-name').textContent=user.displayName||user.username||'Usuário';$('#profile-username').textContent=user.username?`@${user.username}`:'';$('#profile-bio').textContent=user.bio||'Sem bio ainda.';$('#profile-avatar').innerHTML=avatarMarkup(user);$('#profile-visibility').textContent=user.isPublic?'Público':'Privado';const form=$('#profile-form');form.elements.displayName.value=user.displayName||user.username||'';form.elements.avatar.value=avatarPaths[user.avatar]?user.avatar:'gamer';form.elements.bio.value=user.bio||'';form.elements.isPublic.value=String(user.isPublic);}
function renderSummary(summary={}){$('#summary').innerHTML=`<article><strong>${formatPlaytime(summary.totalSeconds)}</strong><span>Tempo total</span></article><article><strong>${summary.gamesPlayed||0}</strong><span>Jogos jogados</span></article><article><strong>${escape(summary.mostPlayed?.title||'—')}</strong><span>Mais jogado</span></article><article><strong>${escape(summary.lastPlayed?.title||'—')}</strong><span>Último jogo</span></article>`;}
function rank(){return [...games].sort((a,b)=>Number(b.totalSeconds)-Number(a.totalSeconds)).slice(0,5).map((game,index)=>`<div class="rank-row"><b>${index+1}</b>${game.cover?`<img class="ranking-cover" src="${escape(game.cover)}" alt="" loading="lazy">`:'<span class="ranking-cover"></span>'}<span>${escape(game.title)}</span><strong>${formatPlaytime(game.totalSeconds)}</strong></div>`).join('')||'<p class="muted">Jogue para começar seu ranking.</p>';}
function renderTrophies(){const earned=new Map(trophies.map(item=>[item.id,item]));$('#profile-trophies').innerHTML=trophyRegistry.map(t=>{const row=earned.get(t.id);return `<article class="game-row ${row?'':'is-locked'}"><span>${escape(t.icon)}</span><div><strong>${escape(t.name)}</strong><br><small>${escape(t.description)}</small></div>${row?`<label><input type="checkbox" data-pin-trophy="${escape(t.id)}" ${row.pinned?'checked':''}> Fixar</label>`:'<span class="muted">Bloqueado</span>'}</article>`}).join('');}
function renderGames(){$('#profile-games').innerHTML=games.map(game=>`<article class="game-row">${game.cover?`<img class="game-cover" src="${escape(game.cover)}" alt="" loading="lazy" decoding="async">`:'<div class="game-cover"></div>'}<div><strong>${escape(game.title)}</strong><br><small class="muted">${escape(game.system)}</small></div><span>${formatPlaytime(game.totalSeconds)}</span><span class="muted">${game.sessions} sessões · ${new Date(game.lastPlayedAt).toLocaleDateString('pt-BR')}</span></article>`).join('')||'<p class="muted">Nenhum jogo registrado ainda.</p>';}
async function load(){try{const data=await call('/api/profile');games=data.games||[];trophies=data.trophies||[];trophyRegistry=data.trophyRegistry||[];renderIdentity(data.user);renderSummary(data.summary);renderTrophies();$('#ranking').innerHTML=rank();renderGames();$('#profile-status').textContent='Perfil sincronizado.';}catch(error){$('#profile-status').textContent=error.message;}}
$('#edit-profile').onclick=()=>{$('#profile-editor').hidden=!$('#profile-editor').hidden;};
$('#profile-visibility').onclick=()=>{const form=$('#profile-form');form.elements.isPublic.value=String(!profile.isPublic);$('#profile-editor').hidden=false;form.elements.isPublic.focus();};
$('#profile-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const result=await call('/api/profile',{method:'PUT',...writeOptions,body:JSON.stringify({displayName:form.elements.displayName.value,avatar:form.elements.avatar.value,bio:form.elements.bio.value,isPublic:form.elements.isPublic.value==='true'})});renderIdentity(result.user);$('#profile-editor').hidden=true;$('#profile-status').textContent='Perfil salvo no D1.';}catch(error){$('#profile-status').textContent=error.message;}finally{button.disabled=false;}};
$('#export-history').onclick=async()=>{const blob=new Blob([JSON.stringify(await call('/api/player/export'),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plumpgames-historico.json';a.click();URL.revokeObjectURL(a.href);};
$('#delete-history').onclick=async()=>{if(confirm('Apagar definitivamente seu histórico de jogos?')){await call('/api/player/history',{method:'DELETE',headers:writeOptions.headers});location.reload();}};
$('#logout').onclick=async()=>{await call('/api/auth/logout',{method:'POST',...writeOptions,body:'{}'});location.href='/';};
$('#change-password').onsubmit=async event=>{event.preventDefault();try{await call('/api/auth/change-password',{method:'POST',...writeOptions,body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();$('#profile-status').textContent='Senha alterada.';}catch(error){$('#profile-status').textContent=error.message;}};
load();

document.addEventListener('change',async event=>{if(!event.target.matches('[data-pin-trophy]'))return;const ids=[...document.querySelectorAll('[data-pin-trophy]:checked')].map(input=>input.dataset.pinTrophy);if(ids.length>3){event.target.checked=false;return void ($('#profile-status').textContent='Escolha no máximo 3 troféus.');}await call('/api/player/trophies/pinned',{method:'PUT',...writeOptions,body:JSON.stringify({ids})});trophies.forEach(t=>t.pinned=ids.includes(t.id)?1:0);$('#profile-status').textContent='Troféus exibidos atualizados.';});

function friendRow(user,{search=false}={}){const presence=user.presence||{},status=presence.currentGameTitle?`Jogando ${escape(presence.currentGameTitle)}`:presence.online?'Online':presence.lastSeenAt?`Offline — visto em ${new Date(presence.lastSeenAt).toLocaleString('pt-BR')}`:'Offline';let actions=search?`<button data-friend-action="request" data-user-id="${user.id}">Adicionar</button>`:user.status==='pending'&&user.incoming?`<button data-friend-action="accept" data-user-id="${user.id}">Aceitar</button><button data-friend-action="reject" data-user-id="${user.id}">Rejeitar</button>`:user.status==='accepted'?`<button data-friend-action="remove" data-user-id="${user.id}">Remover</button><button data-friend-action="block" data-user-id="${user.id}">Bloquear</button>`:`<span>${escape(user.status)}</span>`;return `<article class="friend-row"><div class="friend-avatar">${avatarMarkup(user)}</div><div><strong>${escape(user.displayName)}</strong><br><small>@${escape(user.username)} · ${status}</small></div><div class="friend-actions">${actions}</div></article>`;}
async function loadFriends(){const data=await call('/api/friends');$('#friends-list').innerHTML=data.friends.map(user=>friendRow(user)).join('')||'<p class="muted">Nenhum amigo ainda.</p>';}
$('#load-friends').onclick=async()=>{const panel=$('#friends-panel');panel.hidden=!panel.hidden;if(!panel.hidden)await loadFriends();};
$('#friend-search-form').onsubmit=async event=>{event.preventDefault();const q=new FormData(event.currentTarget).get('q'),data=await call(`/api/friends/search?q=${encodeURIComponent(q)}`);$('#friend-search-results').innerHTML=data.users.map(user=>friendRow(user,{search:true})).join('')||'<p class="muted">Nenhuma conta encontrada.</p>';};
document.addEventListener('click',async event=>{const button=event.target.closest('[data-friend-action]');if(!button)return;button.disabled=true;try{await call(`/api/friends/${button.dataset.friendAction}`,{method:'POST',...writeOptions,body:JSON.stringify({userId:Number(button.dataset.userId)})});await loadFriends();$('#profile-status').textContent='Amigos atualizados.';}catch(error){$('#profile-status').textContent=error.message;}finally{button.disabled=false;}});
