(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const PREF='plumpgames.preferences.v1', PROFILES='plumpgames.localProfiles.v1', ACTIVE='plumpgames.activeProfile.v1';
const usernamePattern=/^[a-z0-9._-]{3,24}$/;
const themes={original:['#8b5cf6','#4776ff','#38d9f5','#050611','#0d1021','#f5f6ff','#7055ed','#38d9f5'],blue:['#2563eb','#06b6d4','#67e8f9','#04111f','#0b2036','#eefaff','#0ea5e9','#22d3ee'],purple:['#a855f7','#7c3aed','#f0abfc','#10051c','#1d0b31','#fff7ff','#9333ea','#d946ef'],red:['#ef4444','#f97316','#facc15','#160606','#2a1010','#fff7ed','#dc2626','#fb7185'],green:['#22c55e','#16a34a','#86efac','#020b06','#07180d','#ecfdf5','#15803d','#4ade80'],light:['#4f46e5','#0284c7','#0891b2','#f6f7fb','#ffffff','#101422','#4f46e5','#60a5fa'],dark:['#7c3aed','#2563eb','#22d3ee','#030712','#111827','#f9fafb','#6d28d9','#38bdf8']};
const keys=['primary','secondary','accent','background','surface','text','button','glow'];
const defaults={theme:'original',colors:themes.original,glowStrength:.42,cardOpacity:.92,animationStrength:1,view:'detailed',wallpaper:'cosmic',reduceMotion:matchMedia('(prefers-reduced-motion: reduce)').matches};
let prefs=read(PREF,defaults), editing=null, lastFocus=null;
function read(k,f){try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return {...f}}}
function profiles(){try{const value=JSON.parse(localStorage.getItem(PROFILES)||'[]');return Array.isArray(value)?value.map(p=>({displayName:p.displayName,username:String(p.username||'').trim().toLowerCase(),avatar:p.avatar,bio:p.bio,createdAt:p.createdAt})).filter(p=>usernamePattern.test(p.username)):[]}catch{return []}}
function toast(m){const t=$('.toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function normalizeInputs(){[...$$('#local-username,#admin-username')].forEach(i=>i.addEventListener('input',()=>{i.value=i.value.trim().toLowerCase().replace(/\s/g,'')}))}
function apply(){keys.forEach((k,i)=>document.documentElement.style.setProperty(`--color-${k}`,prefs.colors[i]));document.documentElement.style.setProperty('--glow-strength',prefs.glowStrength);document.documentElement.style.setProperty('--card-opacity',prefs.cardOpacity);document.documentElement.style.setProperty('--animation-strength',prefs.reduceMotion?0:prefs.animationStrength);document.body.classList.toggle('reduce-animations',prefs.reduceMotion);$('#games-list').dataset.view=prefs.view;$$('[data-view-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.viewMode===prefs.view)));renderWallpaper()}
function sync(){ $('#theme-select').value=prefs.theme;keys.forEach((k,i)=>$(`#color-${k}`).value=prefs.colors[i]);$('#glow-strength').value=prefs.glowStrength;$('#card-opacity').value=prefs.cardOpacity;$('#animation-strength').value=prefs.animationStrength;$('#reduce-animations').checked=prefs.reduceMotion }
function collect(){prefs.theme=$('#theme-select').value;prefs.colors=keys.map(k=>$(`#color-${k}`).value);prefs.glowStrength=+$('#glow-strength').value;prefs.cardOpacity=+$('#card-opacity').value;prefs.animationStrength=+$('#animation-strength').value;prefs.reduceMotion=$('#reduce-animations').checked}
function save(){localStorage.setItem(PREF,JSON.stringify(prefs))}
const wallpapers={cosmic:['Gradiente Cósmico','Gradiente suave em movimento','Baixo'],particles:['Partículas Neon','Pontos luminosos flutuantes','Médio'],waves:['Ondas Digitais','Ondas neon contínuas','Médio'],none:['Sem animação','Fundo estático e econômico','Nenhum']};
function renderWallpaper(){const el=$('#live-wallpaper');el.className=`live-wallpaper wallpaper--${prefs.wallpaper}`;el.classList.toggle('is-paused',document.hidden||prefs.reduceMotion||prefs.wallpaper==='none')}
function buildWallpapers(){const box=$('#wallpaper-selector');box.innerHTML=Object.entries(wallpapers).map(([id,x])=>`<article class="wallpaper-card"><div class="wallpaper-thumb wallpaper--${id}" aria-hidden="true"></div><div><strong>${x[0]}</strong><small>${x[1]}</small><small>Impacto: ${x[2]}</small></div><button class="button button--small ${prefs.wallpaper===id?'button--primary':'button--ghost'}" data-wallpaper="${id}">Selecionar</button></article>`).join('');$$('[data-wallpaper]',box).forEach(b=>b.onclick=()=>{prefs.wallpaper=b.dataset.wallpaper;save();apply();buildWallpapers();toast('Live wallpaper selecionado.')})}
function openPanel(){lastFocus=document.activeElement;$('#gx-side-panel').hidden=false;$('#gx-panel-backdrop').hidden=false;$('#gx-menu-button').setAttribute('aria-expanded','true');document.body.classList.add('modal-open');$('#gx-panel-close').focus()}
function closePanel(){if($('#gx-side-panel').hidden)return;$('#gx-side-panel').hidden=true;$('#gx-panel-backdrop').hidden=true;$('#gx-menu-button').setAttribute('aria-expanded','false');document.body.classList.remove('modal-open');(lastFocus||$('#gx-menu-button')).focus()}
function account(){const list=profiles(), active=list.find(p=>p.username===localStorage.getItem(ACTIVE));const a=$('#account-area');if(active)a.innerHTML=`<div class="profile-summary"><span>${active.avatar}</span><div><h3>${active.displayName}</h3><small>@${active.username}</small></div></div><p>Este perfil existe apenas neste navegador e não é uma conta online segura.</p><button class="button button--ghost" data-edit-profile>Editar perfil local</button><button class="button button--ghost" data-delete-profile>Excluir perfil local</button>`;else a.innerHTML=`<h3>Bem-vindo à PlumpGames</h3><p>Entre, crie um usuário local ou continue como visitante.</p><button class="button button--ghost" data-existing>Entrar</button><button class="button button--primary" data-create-profile>Criar usuário</button><button class="button button--ghost" data-visitor>Continuar como visitante</button><small>Este perfil fica salvo somente neste navegador.</small>`;
$('[data-create-profile]',a)?.addEventListener('click',()=>openProfile());$('[data-edit-profile]',a)?.addEventListener('click',()=>openProfile(active));$('[data-delete-profile]',a)?.addEventListener('click',()=>{localStorage.setItem(PROFILES,JSON.stringify(list.filter(p=>p.username!==active.username)));localStorage.removeItem(ACTIVE);account();toast('Perfil local excluído.')});$('[data-visitor]',a)?.addEventListener('click',closePanel);$('[data-existing]',a)?.addEventListener('click',()=>{if(!list.length)return toast('Nenhum perfil existe neste navegador.');a.innerHTML='<h3>Entrar como usuário existente deste navegador</h3>'+list.map(p=>`<button class="local-profile-choice" data-choose="${p.username}">${p.avatar} ${p.displayName} <small>@${p.username}</small></button>`).join('');$$('[data-choose]',a).forEach(b=>b.onclick=()=>{let username=b.dataset.choose.trim().toLowerCase();localStorage.setItem(ACTIVE,username);account();toast('Perfil local restaurado.')})})}
function openProfile(p=null){editing=p?.username||null;$('#profile-title').textContent=p?'Editar perfil local':'Criar usuário local';$('#display-name').value=p?.displayName||'';$('#local-username').value=p?.username||'';$('#profile-avatar').value=p?.avatar||'🎮';$('#profile-bio').value=p?.bio||'';$('#profile-modal').hidden=false;$('#display-name').focus()}
function closeProfile(){$('#profile-modal').hidden=true;$('#profile-error').textContent=''}
async function adminSession(){try{const r=await fetch('/api/admin/session',{credentials:'same-origin'}),d=await r.json();const ok=d.authenticated===true&&d.role==='admin';$('#admin-area').hidden=ok;$('#editor-area').hidden=!ok;return ok}catch{$('#admin-area').hidden=false;$('#editor-area').hidden=true;return false}}
function modal(title,content,download=false){$('#modal-title').textContent=title;$('#modal-content').innerHTML=content;$('#modal-actions').innerHTML=download?'<button class="button button--ghost" data-close-modal>Cancelar</button><a class="button button--primary" href="https://github.com/kiwifypurplehero-cell/CS1-6HTML/archive/refs/heads/main.zip">Continuar download</a>':'<button class="button button--primary" data-close-modal>Entendido</button>';$('#site-modal').hidden=false}
function init(){normalizeInputs();apply();sync();buildWallpapers();account();adminSession();
$('#gx-menu-button').onclick=()=>$('#gx-side-panel').hidden?openPanel():closePanel;$('#gx-panel-close').onclick=closePanel;$('#gx-panel-backdrop').onclick=closePanel;
$$('.gx-accordion__button').forEach(b=>b.onclick=()=>{const opening=b.getAttribute('aria-expanded')!=='true';if(innerWidth<700)$$('.gx-accordion__button').forEach(x=>{x.setAttribute('aria-expanded','false');$('#'+x.getAttribute('aria-controls')).hidden=true});b.setAttribute('aria-expanded',String(opening));$('#'+b.getAttribute('aria-controls')).hidden=!opening});
$('#theme-select').onchange=e=>{if(e.target.value!=='custom'){prefs.theme=e.target.value;prefs.colors=themes[prefs.theme];sync();apply()}};$$('#appearance-content input[type=color]').forEach(i=>i.oninput=()=>{$('#theme-select').value='custom';prefs.theme='custom'});$('#apply-theme').onclick=()=>{collect();apply();toast('Aparência aplicada.')};$('#save-theme').onclick=()=>{collect();apply();save();toast('Preferências salvas neste navegador.')};$('#reset-theme').onclick=()=>{prefs={...defaults,colors:[...themes.original]};save();sync();apply();buildWallpapers();toast('Configurações restauradas.')};$$('[data-view-mode]').forEach(b=>b.onclick=()=>{prefs.view=b.dataset.viewMode;save();apply()});$('#reduce-animations').onchange=e=>{prefs.reduceMotion=e.target.checked;save();apply()};document.addEventListener('visibilitychange',renderWallpaper);
$('#profile-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);let username=String(fd.get('username')).trim().toLowerCase();if(!usernamePattern.test(username))return $('#profile-error').textContent='Use 3 a 24 letras minúsculas, números, ponto, hífen ou underline, sem espaços.';const list=profiles();if(list.some(p=>p.username===username&&p.username!==editing))return $('#profile-error').textContent='Este nome de usuário já existe neste navegador.';const profile={displayName:String(fd.get('displayName')).trim(),username,avatar:String(fd.get('avatar')),bio:String(fd.get('bio')).trim(),createdAt:list.find(p=>p.username===editing)?.createdAt||new Date().toISOString()};localStorage.setItem(PROFILES,JSON.stringify([...list.filter(p=>p.username!==editing),profile]));localStorage.setItem(ACTIVE,username);closeProfile();account();toast('Perfil local salvo neste navegador.')};$$('[data-close-profile]').forEach(b=>b.onclick=closeProfile);
$('#admin-login-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);let username=String(fd.get('username')).trim().toLowerCase();const message=$('#admin-message');message.textContent='Verificando…';try{const r=await fetch('/api/admin/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:String(fd.get('password'))})});const d=await r.json();message.textContent=r.ok?'':(d.error||'Usuário ou senha inválidos.');if(r.ok){e.target.reset();await adminSession();toast('Modo editor ativado.')}}catch{message.textContent='Não foi possível entrar agora.'}};$('#admin-logout').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST',credentials:'same-origin'});await adminSession();toast('Sessão administrativa encerrada.')};
const future=['Contas sincronizadas','Biblioteca de jogos','Favoritos','Conquistas','Comentários','Perfis públicos','Sincronização entre dispositivos','Editor administrativo permanente'];$('#future-content').innerHTML=future.map(x=>`<button class="future-card" type="button"><b>${x}</b><span>Em desenvolvimento</span></button>`).join('');$$('.future-card').forEach(b=>b.onclick=()=>toast('Este recurso está planejado para uma versão futura.'));const tools=['Editar nome e descrição dos jogos','Editar status do projeto','Editar notícias','Editar links','Editar data ou texto de destaque','Adicionar conteúdo futuro','Pré-visualizar alterações'];$('.editor-tools').innerHTML=tools.map(x=>`<button class="button button--ghost" type="button">${x}</button>`).join('');$$('.editor-tools button').forEach(b=>b.onclick=()=>toast('Ferramenta demonstrativa: não há persistência permanente.'));
$$('[data-open-download]').forEach(b=>b.onclick=()=>modal('Confirmar download','<p>Você baixará a versão mais recente diretamente do GitHub.</p>',true));$('[data-open-install]').onclick=()=>modal('Como instalar o CS 1.6 PLH','<ol><li>Baixe e extraia o ZIP.</li><li>Abra o arquivo HTML principal em um navegador atualizado.</li></ol>');$('[data-open-credits]').onclick=()=>modal('Créditos','<p>PlumpGames foi criada por Matheus (Plump), com ajuda do Codex.</p>');$('[data-open-privacy]').onclick=()=>modal('Política de Privacidade','<p>Perfis e preferências locais ficam somente neste navegador. A sessão administrativa usa cookie seguro HttpOnly.</p>');$('[data-open-terms]').onclick=()=>modal('Termos de Uso','<p>Use a PlumpGames de forma lícita e respeitosa.</p>');$('#site-modal').onclick=e=>{if(e.target.closest('[data-close-modal]'))$('#site-modal').hidden=true};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#profile-modal').hidden)closeProfile();else if(!$('#site-modal').hidden)$('#site-modal').hidden=true;else closePanel()}const trap=!$('#profile-modal').hidden?$('#profile-modal'):(!$('#site-modal').hidden?$('#site-modal'):(!$('#gx-side-panel').hidden?$('#gx-side-panel'):null));if(e.key==='Tab'&&trap){const f=$$('button:not([disabled]),a[href],input,select,textarea',trap).filter(x=>!x.closest('[hidden]'));if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});$$('.reveal,.hero-entrance').forEach(x=>x.classList.add('visible'))}
init();
})();
