(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const PREF='plumpgames.preferences.v2', VISITOR='plumpgames.visitor', usernamePattern=/^[a-z0-9._-]{3,24}$/;
const themes={original:['#8b5cf6','#4776ff','#38d9f5','#050611','#0d1021','#f5f6ff','#7055ed','#38d9f5'],blue:['#2563eb','#06b6d4','#67e8f9','#04111f','#0b2036','#eefaff','#0ea5e9','#22d3ee'],purple:['#a855f7','#7c3aed','#f0abfc','#10051c','#1d0b31','#fff7ff','#9333ea','#d946ef'],dark:['#7c3aed','#2563eb','#22d3ee','#030712','#111827','#f9fafb','#6d28d9','#38bdf8']};
const keys=['primary','secondary','accent','background','surface','text','button','glow'];
const defaults={theme:'original',colors:themes.original,glowStrength:.42,cardOpacity:.92,animationStrength:1,view:'detailed',wallpaper:'cosmic',reduceMotion:matchMedia('(prefers-reduced-motion: reduce)').matches};
let prefs=readPrefs(), currentUser=null, authBusy=false, registerStep=1, lastFocus=null;
function readPrefs(){try{return {...defaults,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch{return {...defaults}}}
function savePrefs(){localStorage.setItem(PREF,JSON.stringify(prefs))}
function toast(message){const node=$('.toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600)}
function normalizeUsernameInput(input){input.value=input.value.trim().toLowerCase().replace(/\s/g,'')}
function apply(){const colors=prefs.colors||themes[prefs.theme]||themes.original;keys.forEach((key,index)=>document.documentElement.style.setProperty(`--color-${key}`,colors[index]));document.documentElement.style.setProperty('--glow-strength',prefs.glowStrength);document.documentElement.style.setProperty('--card-opacity',prefs.cardOpacity);document.documentElement.style.setProperty('--animation-strength',prefs.reduceMotion?0:prefs.animationStrength);document.body.classList.toggle('reduce-animations',prefs.reduceMotion);$('#games-list').dataset.view=prefs.view;$$('[data-view-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.viewMode===prefs.view)));renderWallpaper()}
function sync(){ $('#theme-select').value=prefs.theme;keys.forEach((key,index)=>$(`#color-${key}`).value=(prefs.colors||themes.original)[index]);$('#glow-strength').value=prefs.glowStrength;$('#card-opacity').value=prefs.cardOpacity;$('#animation-strength').value=prefs.animationStrength;$('#reduce-animations').checked=prefs.reduceMotion }
function collect(){prefs.theme=$('#theme-select').value;prefs.colors=keys.map(key=>$(`#color-${key}`).value);prefs.glowStrength=+$('#glow-strength').value;prefs.cardOpacity=+$('#card-opacity').value;prefs.animationStrength=+$('#animation-strength').value;prefs.reduceMotion=$('#reduce-animations').checked}
const wallpapers={cosmic:['Gradiente Cósmico','Gradiente suave em movimento','Baixo'],particles:['Partículas Neon','Pontos luminosos flutuantes','Médio'],waves:['Ondas Digitais','Ondas neon contínuas','Médio'],none:['Sem animação','Fundo estático','Nenhum']};
function renderWallpaper(){const node=$('#live-wallpaper');node.className=`live-wallpaper wallpaper--${prefs.wallpaper}`;node.classList.toggle('is-paused',document.hidden||prefs.reduceMotion||prefs.wallpaper==='none')}
function buildWallpapers(){const box=$('#wallpaper-selector');box.innerHTML=Object.entries(wallpapers).map(([id,item])=>`<article class="wallpaper-card"><div class="wallpaper-thumb wallpaper--${id}" aria-hidden="true"></div><div><strong>${item[0]}</strong><small>${item[1]}</small><small>Impacto: ${item[2]}</small></div><button class="button button--small ${prefs.wallpaper===id?'button--primary':'button--ghost'}" data-wallpaper="${id}">Selecionar</button></article>`).join('');$$('[data-wallpaper]',box).forEach(button=>button.onclick=()=>{prefs.wallpaper=button.dataset.wallpaper;savePrefs();apply();buildWallpapers()})}
function avatar(id){return {controller:'🎮',rocket:'🚀',alien:'👾',bolt:'⚡'}[id]||'🎮'}
function renderAccount(){const area=$('#account-area'), editor=$('#editor-area');if(!currentUser){area.innerHTML='<h3>Bem-vindo à PlumpGames</h3><p>Navegue como visitante ou acesse sua conta.</p><div class="account-actions"><button class="button button--primary" data-open-auth>Entrar / Criar conta</button><button class="button button--ghost" data-menu-visitor>Continuar como visitante</button></div>';editor.hidden=true}else{const badge=currentUser.role==='admin'?'<span class="admin-badge">ADMIN</span>':'';area.innerHTML=`<div class="profile-summary"><span>${avatar(currentUser.avatar)}</span><div><h3>${escapeHtml(currentUser.displayName)} ${badge}</h3><small>@${escapeHtml(currentUser.username)}</small></div></div><div class="account-actions"><button class="button button--ghost" data-edit-account>Editar perfil</button><button class="button button--ghost" data-logout>Sair</button></div>`;editor.hidden=currentUser.role!=='admin'}$('[data-open-auth]',area)?.addEventListener('click',()=>openAuth('login'));$('[data-menu-visitor]',area)?.addEventListener('click',closePanel);$('[data-edit-account]',area)?.addEventListener('click',()=>toast('Edição de perfil estará disponível em breve.'));$('[data-logout]',area)?.addEventListener('click',logout)}
function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}
function openPanel(){lastFocus=document.activeElement;$('#gx-side-panel').hidden=false;$('#gx-panel-backdrop').hidden=false;$('#gx-menu-button').setAttribute('aria-expanded','true');document.body.classList.add('modal-open');$('#gx-panel-close').focus()}
function closePanel(){if($('#gx-side-panel').hidden)return;$('#gx-side-panel').hidden=true;$('#gx-panel-backdrop').hidden=true;$('#gx-menu-button').setAttribute('aria-expanded','false');document.body.classList.remove('modal-open');(lastFocus||$('#gx-menu-button')).focus()}
function selectAuthTab(tab){const login=tab==='login';$('#login-tab').setAttribute('aria-selected',String(login));$('#register-tab').setAttribute('aria-selected',String(!login));$('#login-panel').hidden=!login;$('#register-panel').hidden=login;$('#auth-title').textContent=login?'Entrar na PlumpGames':'Criar conta na PlumpGames';(login?$('#login-username'):$('[name=username]',$('#register-form'))).focus()}
function openAuth(tab='login'){lastFocus=document.activeElement;$('#auth-modal').hidden=false;document.body.classList.add('modal-open');selectAuthTab(tab)}
function closeAuth(){if(authBusy)return;$('#auth-modal').hidden=true;document.body.classList.remove('modal-open');lastFocus?.focus()}
function showRegisterStep(step){registerStep=step;$$('.register-step').forEach(node=>node.hidden=Number(node.dataset.step)!==step);$('#register-progress').textContent=`Etapa ${step} de 4`;$('#register-back').hidden=step===1;$('#register-next').hidden=step===4;$('#register-submit').hidden=step!==4;if(step===4)buildSummary()}
function validateStep(){const form=$('#register-form'), message=$('.form-message',form);message.textContent='';if(registerStep===1){const username=form.elements.username;normalizeUsernameInput(username);if(!usernamePattern.test(username.value)){message.textContent='Use 3 a 24 letras minúsculas, números, ponto, hífen ou underline.';return false}if(!form.elements.email.checkValidity()){message.textContent='Informe um e-mail válido.';return false}if(form.elements.password.value.length<8){message.textContent='A senha deve ter no mínimo 8 caracteres.';return false}if(form.elements.password.value!==form.elements.confirmPassword.value){message.textContent='As senhas não coincidem.';return false}}if(registerStep===2&&!form.elements.displayName.value.trim()){message.textContent='Informe um nome de exibição.';return false}return true}
function buildSummary(){const form=$('#register-form'), data=new FormData(form);$('#register-summary').innerHTML=`<p><b>Username:</b> @${escapeHtml(String(data.get('username')).trim().toLowerCase())}</p><p><b>Nome:</b> ${escapeHtml(data.get('displayName'))}</p><p><b>Avatar:</b> ${avatar(data.get('avatar'))}</p><p><b>Visibilidade:</b> ${form.elements.isPublic.checked?'Público':'Privado'}</p><p><b>Tema:</b> ${escapeHtml(data.get('theme'))}</p>`}
async function api(path, options={}){const response=await fetch(path,{credentials:'same-origin',...options});let data={};try{data=await response.json()}catch{}return {response,data}}
async function restoreSession(){try{const {response,data}=await api('/api/auth/session');if(response.ok&&data.authenticated)currentUser=data.user;else currentUser=null}catch{currentUser=null;toast('Não foi possível conectar ao servidor.')}finally{$('#session-loading').hidden=true;renderAccount();if(!currentUser&&!sessionStorage.getItem(VISITOR))openAuth('login')}}
async function logout(){try{await api('/api/auth/logout',{method:'POST'});currentUser=null;renderAccount();closePanel();openAuth('login');toast('Sessão encerrada.')}catch{toast('Não foi possível conectar ao servidor.')}}
function modal(title,content,download=false){$('#modal-title').textContent=title;$('#modal-content').innerHTML=content;$('#modal-actions').innerHTML=download?'<button class="button button--ghost" data-close-modal>Cancelar</button><a class="button button--primary" href="https://github.com/kiwifypurplehero-cell/CS1-6HTML/archive/refs/heads/main.zip">Continuar download</a>':'<button class="button button--primary" data-close-modal>Entendido</button>';$('#site-modal').hidden=false}
function bindAuth(){['#login-username','#register-form [name=username]'].forEach(selector=>$(selector).addEventListener('input',event=>normalizeUsernameInput(event.target)));$('#login-tab').onclick=()=>selectAuthTab('login');$('#register-tab').onclick=()=>selectAuthTab('register');$$('[data-toggle-password]').forEach(button=>button.onclick=()=>{const input=$('#'+button.dataset.togglePassword), showing=input.type==='text';input.type=showing?'password':'text';button.textContent=showing?'Mostrar':'Ocultar'});$('[data-forgot]').onclick=()=>toast('A recuperação de senha estará disponível em uma versão futura.');$('[data-close-auth]').onclick=closeAuth;$('[data-continue-visitor]').onclick=()=>{sessionStorage.setItem(VISITOR,'1');closeAuth();toast('Você está navegando como visitante.')};$('#register-next').onclick=()=>{if(validateStep())showRegisterStep(registerStep+1)};$('#register-back').onclick=()=>showRegisterStep(registerStep-1);
$('#login-form').onsubmit=async event=>{event.preventDefault();if(authBusy)return;const form=event.currentTarget,message=$('.form-message',form),username=form.elements.username.value.trim().toLowerCase();if(!usernamePattern.test(username)){message.textContent='Usuário ou senha inválidos.';return}authBusy=true;form.querySelector('[type=submit]').disabled=true;message.textContent='Entrando…';try{const {response,data}=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:form.elements.password.value,remember:form.elements.remember.checked})});if(!response.ok){message.textContent=data.error||'Usuário ou senha inválidos.';return}currentUser=data.user;form.reset();authBusy=false;closeAuth();renderAccount();toast('Login realizado com sucesso.')}catch{message.textContent='Não foi possível conectar ao servidor.'}finally{authBusy=false;form.querySelector('[type=submit]').disabled=false}};
$('#register-form').onsubmit=async event=>{event.preventDefault();if(authBusy||registerStep!==4)return;const form=event.currentTarget,message=$('.form-message',form),data=new FormData(form);authBusy=true;$('#register-submit').disabled=true;message.textContent='Criando conta…';const payload={username:String(data.get('username')).trim().toLowerCase(),email:data.get('email'),password:data.get('password'),displayName:data.get('displayName'),avatar:data.get('avatar'),bio:data.get('bio'),isPublic:form.elements.isPublic.checked,remember:form.elements.remember.checked,preferences:{theme:data.get('theme'),wallpaper:data.get('wallpaper'),animations:form.elements.animations.checked,view:data.get('view'),reduceMotion:form.elements.reduceMotion.checked}};try{const {response,result,data:unused}=await Promise.resolve(api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).then(x=>({response:x.response,result:x.data,data:null}));if(!response.ok){message.textContent=result.error||'Não foi possível criar a conta.';return}currentUser=result.user;authBusy=false;prefs={...prefs,...payload.preferences,colors:themes[payload.preferences.theme]||themes.original};savePrefs();apply();form.reset();showRegisterStep(1);closeAuth();renderAccount();toast('Conta criada com sucesso.')}catch{message.textContent='Não foi possível conectar ao servidor.'}finally{authBusy=false;$('#register-submit').disabled=false}}}
function init(){apply();sync();buildWallpapers();renderAccount();bindAuth();showRegisterStep(1);$('#gx-menu-button').onclick=()=>$('#gx-side-panel').hidden?openPanel():closePanel;$('#gx-panel-close').onclick=closePanel;$('#gx-panel-backdrop').onclick=closePanel;$$('.gx-accordion__button').forEach(button=>button.onclick=()=>{const opening=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(opening));$('#'+button.getAttribute('aria-controls')).hidden=!opening});$('#theme-select').onchange=event=>{if(themes[event.target.value]){prefs.theme=event.target.value;prefs.colors=themes[prefs.theme];sync();apply()}};$('#apply-theme').onclick=()=>{collect();apply()};$('#save-theme').onclick=()=>{collect();apply();savePrefs();toast('Preferências salvas neste navegador.')};$('#reset-theme').onclick=()=>{prefs={...defaults,colors:[...themes.original]};savePrefs();sync();apply();buildWallpapers()};$$('[data-view-mode]').forEach(button=>button.onclick=()=>{prefs.view=button.dataset.viewMode;savePrefs();apply()});$('#reduce-animations').onchange=event=>{prefs.reduceMotion=event.target.checked;savePrefs();apply()};document.addEventListener('visibilitychange',renderWallpaper);
const future=['Biblioteca de jogos','Favoritos','Conquistas','Comentários','Perfis públicos','Sincronização entre dispositivos'];$('#future-content').innerHTML=future.map(item=>`<button class="future-card" type="button"><b>${item}</b><span>Em desenvolvimento</span></button>`).join('');const tools=['Editar jogos','Editar notícias','Alterar status','Gerenciar destaques','Revisar feedbacks','Revisar bugs'];$('.editor-tools').innerHTML=tools.map(item=>`<button class="button button--ghost" type="button">${item}</button>`).join('');$$('.editor-tools button').forEach(button=>button.onclick=async()=>{const {response}=await api('/api/admin/validate');toast(response.ok?'Acesso administrativo validado no servidor.':'Acesso negado pelo servidor.')});$('#save-admin').onclick=()=>toast('Nenhuma alteração pendente.');$$('[data-open-download]').forEach(button=>button.onclick=()=>modal('Confirmar download','<p>Você baixará a versão mais recente diretamente do GitHub.</p>',true));$('[data-open-install]').onclick=()=>modal('Como instalar','<ol><li>Baixe e extraia o ZIP.</li><li>Abra o HTML principal.</li></ol>');$('[data-open-credits]').onclick=()=>modal('Créditos','<p>PlumpGames foi criada por Matheus (Plump), com ajuda do Codex.</p>');$('[data-open-privacy]').onclick=()=>modal('Política de Privacidade','<p>Preferências visuais ficam no navegador. Credenciais e sessões são protegidas no servidor.</p>');$('[data-open-terms]').onclick=()=>modal('Termos de Uso','<p>Use a PlumpGames de forma lícita e respeitosa.</p>');$('#site-modal').onclick=event=>{if(event.target.closest('[data-close-modal]'))$('#site-modal').hidden=true};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!authBusy){if(!$('#auth-modal').hidden)closeAuth();else if(!$('#site-modal').hidden)$('#site-modal').hidden=true;else closePanel()}const trap=!$('#auth-modal').hidden?$('#auth-modal'):(!$('#gx-side-panel').hidden?$('#gx-side-panel'):null);if(event.key==='Tab'&&trap){const focusable=$$('button:not([disabled]),a[href],input,select,textarea',trap).filter(node=>!node.closest('[hidden]'));if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});$$('.reveal,.hero-entrance').forEach(node=>node.classList.add('visible'));restoreSession()}
init();
})();
