const $=selector=>document.querySelector(selector);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const guestKey='plumpgames_guest_library';
let state={recent:[],favorites:[]};
const descriptor=g=>({gameId:g.gameId,title:g.title,system:g.platform||g.system||'Web',source:g.source||'web',sourceKey:g.sourceKey||g.gameId,cover:g.cover||''});
function playUrl(g){if(g.source==='emulator'){const system=(g.platform||'').toUpperCase();return `/Emuladores/${system}/player?game=${encodeURIComponent(String(g.sourceKey||g.gameId).replace(/^(ps1|gbc|gba):/,''))}`;}return `/play.html?repo=${encodeURIComponent(g.sourceKey||g.gameId)}&name=${encodeURIComponent(g.title)}`;}
function card(g){const d=encodeURIComponent(JSON.stringify(descriptor(g)));return `<article class="personal-game" data-game="${d}">${g.cover?`<img src="${escape(g.cover)}" alt="" loading="lazy">`:'<div class="personal-game__cover">🎮</div>'}<div><strong>${escape(g.title)}</strong><small>${escape(g.platform||g.system||g.source)}</small>${g.lastPlayedAt?`<time>${new Date(g.lastPlayedAt).toLocaleString('pt-BR')}</time>`:''}</div><div class="personal-game__actions"><button data-feedback="1" aria-label="Curtir">👍</button><button data-favorite aria-label="Favoritar" aria-pressed="${Boolean(g.favorite)}">${g.favorite?'★':'☆'}</button><button data-feedback="-1" aria-label="Não curtir">👎</button><a href="${escape(playUrl(g))}" target="_blank" rel="noopener" data-personal-play>Jogar</a></div></article>`;}
function render(){const empty='<p class="workspace-empty">Nada aqui ainda. Inicie um jogo na área Emuladores ou no catálogo.</p>';$('#workspace-recent').innerHTML=state.recent.map(card).join('')||empty;$('#workspace-favorites').innerHTML=state.favorites.map(card).join('')||empty;$('#workspace-feedback').innerHTML=state.recent.map(card).join('')||empty;}
async function load(){if(window.plumpUser?.isGuest){state=JSON.parse(sessionStorage.getItem(guestKey)||'{"recent":[],"favorites":[]}');render();$('#workspace-status').textContent='Sessão de visitante: escolhas temporárias.';return;}try{const response=await fetch('/api/player/workspace',{credentials:'include',cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);state=data;render();$('#workspace-status').textContent='Área sincronizada.';}catch(error){$('#workspace-status').textContent=error.message;}}
async function update(game,patch){for(const list of [state.recent,state.favorites]){const item=list.find(x=>x.gameId===game.gameId);if(item)Object.assign(item,patch);}if(patch.favorite&&!state.favorites.some(x=>x.gameId===game.gameId))state.favorites.unshift({...game,...patch});if(!patch.favorite)state.favorites=state.favorites.filter(x=>x.gameId!==game.gameId);render();if(window.plumpUser?.isGuest){sessionStorage.setItem(guestKey,JSON.stringify(state));return;}await fetch('/api/player/preference',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json','X-PlumpGames-Request':'same-origin'},body:JSON.stringify({game:descriptor(game),favorite:Boolean(patch.favorite),rating:patch.rating??game.rating??null})});}
document.addEventListener('click',event=>{const root=event.target.closest('[data-game]');if(!root)return;const game=JSON.parse(decodeURIComponent(root.dataset.game));if(event.target.closest('[data-favorite]'))update(game,{favorite:event.target.getAttribute('aria-pressed')!=='true'});const feedback=event.target.closest('[data-feedback]');if(feedback)update(game,{favorite:Boolean(game.favorite),rating:Number(feedback.dataset.feedback)});});
addEventListener('plumpgames:auth-ready',load);setTimeout(load,500);
