import {EmulatorBootDiagnostics,EmulatorLoadingManager,instrumentFirstFrame} from '../shared/emulator-loading-manager.js';
import {PlaytimeTracker,descriptor,bindEmulatorControls} from '../../playtime-tracker.js';
import {EmulatorViewportManager} from '../shared/emulator-viewport-manager.js';
import {EmulatorInputManager} from '../shared/emulator-input-manager.js';
const DATA='https://cdn.emulatorjs.org/4.2.3/data/', $=selector=>document.querySelector(selector), gameId=new URLSearchParams(location.search).get('game')||'', shell=$('#gbc-player-shell');
let playtime,game,controller,romBlob,objectUrl,loader,disposeFrames,token=0,bootRequested=false,firstFrame=false,compatible=false;
const loading=new EmulatorLoadingManager({profile:'gbc'}),mobile=()=>matchMedia('(pointer:coarse)').matches&&navigator.maxTouchPoints>0;
const boot=new EmulatorBootDiagnostics({system:'gbc',container:'#gbc-emulator',loading,onError:error=>fail(error),debug:new URLSearchParams(location.search).has('debug')});
const inputManager=new EmulatorInputManager({system:'gbc',gameId,mount:$('#controls-settings')});
const viewport=new EmulatorViewportManager({shell,container:$('#gbc-emulator'),nativeWidth:160,nativeHeight:144,debug:new URLSearchParams(location.search).has('debugViewport')}).start();
const log=(message,details)=>details===undefined?console.info(`[GBC-BOOT] ${message}`):console.info(`[GBC-BOOT] ${message}`,details);
function errorText(error){return error?.detail||({runtime_available:'Runtime não carregou',loader_loaded:'Loader não carregou',core_loaded:'Core não carregou',canvas_created:'WebGL não inicializou',content_mounted:'Conteúdo não foi montado',first_frame:'Primeiro frame não apareceu'}[error?.code])||error?.message||String(error);}
function fail(error,current=token){if(current!==token||error?.name==='AbortError')return;loading.fail(error);$('#loading').hidden=true;$('#error').hidden=false;$('#error p').textContent=`Não foi possível concluir a inicialização do emulador. ${errorText(error)}.`;log(error.code||'BOOT_FAILED',{message:error.message});}
async function fullscreen(){try{if(!document.fullscreenElement)await shell.requestFullscreen();try{await screen.orientation?.lock?.('landscape');}catch{}return true;}catch{return false;}}
function destroy({keepRom=true}={}){boot.destroy();loading.clearTimeout();disposeFrames?.();disposeFrames=null;loader?.remove();loader=null;try{window.EJS_emulator?.stop?.();window.EJS_emulator?.destroy?.();}catch{}delete window.EJS_emulator;$('#gbc-emulator').replaceChildren();bootRequested=firstFrame=false;if(!keepRom){romBlob=null;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;}}
function noteFrame(){if(!bootRequested||firstFrame)return;firstFrame=true;playtime?.start();playtime?.markRunning();bindEmulatorControls(window.EJS_emulator,playtime);viewport.fit();log('first frame');boot.running();loading.markFirstFrame();setTimeout(()=>{$('#loading').hidden=true;},300);}
function requestBoot(current){if(bootRequested||current!==token)return;bootRequested=true;loading.completeStep('boot_requested').completeStep('waiting_first_frame');boot.waitingFirstFrame();log('boot requested');try{window.EJS_emulator?.play?.();}catch(error){fail(error,current);}}
async function gate(current){requestBoot(current);if(mobile()&&!document.fullscreenElement)$('#fullscreen-prompt').hidden=false;}
async function download(url,totalHint){const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw new Error('Não foi possível carregar a ROM.');const total=Number(response.headers.get('Content-Length'))||totalHint||0,reader=response.body?.getReader();if(!reader){const blob=await response.blob();loading.setDownloadProgress(100);return blob;}const chunks=[];let loaded=0,last=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;const percent=total?Math.floor(loaded/total*100):0;if(percent-last>=1){last=percent;loading.setDownloadProgress(percent);}}loading.setDownloadProgress(100);return new Blob(chunks,{type:'application/octet-stream'});}
async function launch(current){destroy({keepRom:true});$('#loading').hidden=false;$('#error').hidden=true;loading.completeStep('runtime_available').setPhase('loading_runtime').startTimeout('loader_loaded',10000,'Runtime/loader não carregou');log('runtime loading');
 if(!objectUrl)objectUrl=URL.createObjectURL(romBlob);Object.assign(window,{EJS_player:'#gbc-emulator',EJS_core:'gb',EJS_gameUrl:objectUrl,EJS_pathtodata:DATA,EJS_startOnLoaded:true,EJS_gameName:game.name,EJS_threads:false,EJS_VirtualGamepadSettings:{},EJS_webgl:compatible?false:undefined});
 loader=document.createElement('script');loader.src=`${DATA}loader.js`;loader.onload=()=>{if(current!==token)return;loading.clearTimeout();loading.completeStep('loader_loaded');boot.watchRuntime({current:()=>current===token,onCore:()=>log('core loaded'),onCanvas:()=>{loading.completeStep('input_ready');viewport.schedule();log('canvas created');}});log('loader loaded');log('core requested');};loader.onerror=()=>fail(Object.assign(new Error('Loader do EmulatorJS falhou.'),{code:'runtime_loading',detail:'Etapa: Runtime'}),current);
 window.EJS_onGameStart=()=>{if(current!==token)return;boot.mounted();log('game mounted');gate(current);};
 disposeFrames=instrumentFirstFrame('#gbc-emulator',noteFrame);document.head.append(loader);
}
async function start({reuse=false}={}){const current=++token;controller?.abort();controller=new AbortController();destroy({keepRom:reuse});compatible=false;loading.reset();$('#error').hidden=true;$('#loading').hidden=false;try{if(!romBlob){loading.setPhase('network');const response=await fetch('/api/emulators/gbc/games',{signal:controller.signal}),library=await response.json();if(!response.ok)throw new Error(library.error);game=library.games.find(item=>item.id===gameId);if(!game)throw new Error('Jogo GBC não encontrado.');if(!playtime)playtime=new PlaytimeTracker(descriptor({system:'gbc',id:game.id,title:game.name,cover:game.cover}));$('#game-name').textContent=$('#loading-game').textContent=game.name;document.title=`${game.name} — PlumpGames`;romBlob=await download(`/api/emulators/gbc/file/${encodeURIComponent(game.bootKey)}`,game.size);}else loading.setDownloadProgress(100);await launch(current);}catch(error){fail(error,current);}}
$('#fullscreen-prompt').onclick=async()=>{await fullscreen();$('#fullscreen-prompt').hidden=true;requestBoot(token);};$('#fullscreen').onclick=()=>fullscreen();$('#restart').onclick=()=>start({reuse:true});$('#retry').onclick=()=>start({reuse:true});$('#compatibility').onclick=()=>{compatible=true;launch(++token);};$('#settings-toggle').onclick=()=>{const open=$('#settings').hidden;$('#settings').hidden=!open;$('#settings-backdrop').hidden=!open;};$('#details-toggle').onchange=event=>{localStorage.setItem('emulatorLoadingDetails',event.target.checked?'1':'0');$('#initialization-details').hidden=!event.target.checked;};$('#details-toggle').checked=localStorage.getItem('emulatorLoadingDetails')==='1';$('#initialization-details').hidden=!$('#details-toggle').checked;$('#settings-close').onclick=$('#settings-backdrop').onclick=()=>{inputManager.close();$('#settings').hidden=true;$('#settings-backdrop').hidden=true;};document.addEventListener('visibilitychange',()=>{try{if(document.hidden){window.EJS_emulator?.pause?.();playtime?.markPaused();}else if(bootRequested){window.EJS_emulator?.play?.();if(firstFrame)playtime?.markRunning();}}catch{}});addEventListener('pagehide',()=>{inputManager.destroy();viewport.destroy();controller?.abort();destroy({keepRom:false});});start();
