import {EmulatorBootDiagnostics,EmulatorLoadingManager,instrumentFirstFrame} from '../shared/emulator-loading-manager.js';
import {PlaytimeTracker,descriptor,bindEmulatorControls} from '../../playtime-tracker.js';
import {EmulatorViewportManager} from '../shared/emulator-viewport-manager.js';
import {EmulatorInputManager} from '../shared/emulator-input-manager.js';
const DATA='/Emuladores/vendor/emulatorjs/data/',$=s=>document.querySelector(s),id=new URLSearchParams(location.search).get('game')||'',shell=$('#gba-shell');
let playtime;const loading=new EmulatorLoadingManager({profile:'gbc'});let controller,romUrl,biosUrl,script,dispose,game,attempt=0,compatible=false,started=false,lastFrame=performance.now(),frames=0,fps=0,adaptive=0;
const boot=new EmulatorBootDiagnostics({system:'gba',container:'#gba-emulator',loading,onError:error=>fail(error),debug:new URLSearchParams(location.search).has('debug')});
const inputManager=new EmulatorInputManager({system:'gba',gameId:id,mount:$('#controls-settings')});
const mobile=()=>matchMedia('(pointer:coarse)').matches&&navigator.maxTouchPoints>0;
const viewport=new EmulatorViewportManager({shell,container:$('#gba-emulator'),nativeWidth:240,nativeHeight:160,debug:new URLSearchParams(location.search).has('debugViewport')}).start();
function fail(error,current=attempt){if(current!==attempt||error?.name==='AbortError')return;loading.fail(error);$('#loading').hidden=true;$('#error').hidden=false;$('#error p').textContent=`Não foi possível iniciar: ${error.message||error}`;}
function clean(){boot.destroy();loading.clearTimeout();dispose?.();dispose=null;script?.remove();script=null;try{window.EJS_emulator?.stop?.();window.EJS_emulator?.destroy?.();}catch{}delete window.EJS_emulator;$('#gba-emulator').replaceChildren();started=false;}
async function download(url,size){const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw new Error('Falha ao baixar a ROM.');const total=Number(response.headers.get('Content-Length'))||size,reader=response.body?.getReader();if(!reader)return response.blob();const parts=[];let bytes=0;for(;;){const {done,value}=await reader.read();if(done)break;parts.push(value);bytes+=value.length;loading.setDownloadProgress(total?Math.min(99,bytes/total*100):0);}loading.setDownloadProgress(100);return new Blob(parts,{type:'application/octet-stream'});}
function coreOptions(){const selected=$('#frameskip').value,value=selected==='auto'?adaptive:Number(selected);return {mgba_frameskip:value?'fixed_interval':'disabled',mgba_frameskip_interval:String(value)};}
function launch(current,blob){clean();loading.completeStep('runtime_available').setPhase('loading_runtime').startTimeout('loader_loaded',12000,'Runtime não carregou');romUrl=romUrl||URL.createObjectURL(blob);const threadCapable=crossOriginIsolated&&typeof SharedArrayBuffer==='function';Object.assign(window,{EJS_player:'#gba-emulator',EJS_core:'gba',EJS_gameUrl:romUrl,EJS_pathtodata:DATA,EJS_startOnLoaded:true,EJS_gameName:game.name,EJS_threads:compatible?false:threadCapable,EJS_gameOptions:coreOptions(),EJS_VirtualGamepadSettings:{},EJS_webgl:compatible?false:undefined});if(biosUrl)window.EJS_biosUrl=biosUrl;else delete window.EJS_biosUrl;
 window.EJS_onGameStart=()=>{if(current!==attempt)return;boot.mounted();loading.completeStep('input_ready').completeStep('boot_requested').completeStep('waiting_first_frame');boot.waitingFirstFrame();viewport.schedule();try{window.EJS_emulator?.play?.();}catch(error){fail(error,current);}};dispose=instrumentFirstFrame('#gba-emulator',()=>{if(started)return;started=true;playtime?.start();playtime?.markRunning();bindEmulatorControls(window.EJS_emulator,playtime);viewport.fit();boot.running();loading.markFirstFrame();setTimeout(()=>$('#loading').hidden=true,250);if(mobile())$('#fullscreen-prompt').hidden=false;});script=document.createElement('script');script.src=DATA+'loader.js';script.onload=()=>{if(current!==attempt)return;loading.completeStep('loader_loaded');boot.watchRuntime({current:()=>current===attempt,onCanvas:()=>viewport.schedule()});};script.onerror=()=>fail(Object.assign(new Error('Loader fixo do EmulatorJS não carregou.'),{code:'runtime_loading',detail:'Etapa: Runtime'}),current);document.head.append(script);}
async function start({reuse=false}={}){const current=++attempt;controller?.abort();controller=new AbortController();clean();$('#error').hidden=true;$('#loading').hidden=false;loading.reset();try{const response=await fetch('/api/emulators/gba/games',{signal:controller.signal}),data=await response.json();if(!response.ok)throw new Error(data.error);game=data.games.find(item=>item.id===id);if(!game)throw new Error('Jogo GBA não encontrado.');if(!playtime)playtime=new PlaytimeTracker(descriptor({system:'gba',id:game.id,title:game.name,cover:game.cover}));$('#game-name').textContent=game.name;document.title=`${game.name} — GBA`;let blob;if(reuse&&romUrl){loading.setDownloadProgress(100);blob=new Blob();}else{if(romUrl)URL.revokeObjectURL(romUrl);romUrl='';const estimate=await navigator.storage?.estimate?.();if(estimate&&game.size>estimate.quota-estimate.usage)console.warn('[GBA] espaço local pode ser insuficiente para cache');blob=await download(`/api/emulators/gba/file/${encodeURIComponent(game.bootKey)}`,game.size);}launch(current,blob);}catch(error){fail(error,current);}}
async function fullscreen(){try{await shell.requestFullscreen();try{await screen.orientation?.lock?.('landscape');}catch{}$('#fullscreen-prompt').hidden=true;}catch{}}
function call(method){try{window.EJS_emulator?.[method]?.();}catch(error){console.warn(error);}}
setInterval(()=>{const now=performance.now(),elapsed=now-lastFrame;fps=Math.round(frames*1000/elapsed);frames=0;lastFrame=now;if($('#frameskip').value==='auto'){adaptive=fps>=56?0:fps>=48?1:fps>=38?2:3;}const canvas=$('#gba-emulator canvas'),gl=canvas?.getContext('webgl2')?'WebGL2':canvas?.getContext('webgl')?'WebGL1':'compatível';$('#diagnostics').textContent=`FPS: ${fps}\nFPS alvo: 60\nframe time: ${fps?Math.round(1000/fps):0} ms\ncore: mGBA (EJS gba)\nrenderer: ${gl}\nSharedArrayBuffer: ${typeof SharedArrayBuffer==='function'}\ncrossOriginIsolated: ${crossOriginIsolated}\nthreads: ${Boolean(window.EJS_threads)}\nresolução interna: 240×160\ncanvas: ${canvas?.width||0}×${canvas?.height||0}\nframeskip: ${$('#frameskip').value==='auto'?adaptive:$('#frameskip').value}\ndeviceMemory: ${navigator.deviceMemory||'n/d'}\nhardwareConcurrency: ${navigator.hardwareConcurrency||'n/d'}`;},3000);function count(){frames++;requestAnimationFrame(count)}requestAnimationFrame(count);
$('#settings-toggle').onclick=()=>{$('#settings').hidden=false;$('#backdrop').hidden=false};$('#settings-close').onclick=$('#backdrop').onclick=()=>{inputManager.close();$('#settings').hidden=true;$('#backdrop').hidden=true};$('#fullscreen').onclick=$('#fullscreen-prompt').onclick=fullscreen;$('#retry').onclick=()=>start({reuse:true});$('#compatibility').onclick=()=>{compatible=true;$('#frameskip').value='1';$('#audio').value='stable';start({reuse:true})};$('#restart').onclick=()=>start({reuse:true});$('#save').onclick=()=>call('saveState');$('#load').onclick=()=>call('loadState');$('#diagnostics-toggle').onchange=e=>$('#diagnostics').hidden=!e.target.checked;$('#bios').onchange=e=>{if(biosUrl)URL.revokeObjectURL(biosUrl);const file=e.target.files[0];biosUrl=file?URL.createObjectURL(file):'';$('#bios-status').textContent=file?`BIOS local: ${file.name}. Reinicie para aplicar.`:'Usando o comportamento padrão do core; nenhuma BIOS é baixada.'};document.addEventListener('visibilitychange',()=>{try{if(document.hidden){call('pause');playtime?.markPaused();}else if(started){call('play');playtime?.markRunning();}}catch{}});addEventListener('pagehide',()=>{inputManager.destroy();viewport.destroy();controller?.abort();clean();if(romUrl)URL.revokeObjectURL(romUrl);if(biosUrl)URL.revokeObjectURL(biosUrl)});start();
