import {downloadPs1Content, fetchPs1Game, resolvePs1Launch} from './ps1-utils.js';
import {EmulatorBootDiagnostics,EmulatorLoadingManager} from '../shared/emulator-loading-manager.js';
import {PlaytimeTracker,descriptor,bindEmulatorControls} from '../../playtime-tracker.js';
import {EmulatorViewportManager} from '../shared/emulator-viewport-manager.js';
import {EmulatorInputManager} from '../shared/emulator-input-manager.js';

const DATA='https://cdn.emulatorjs.org/4.2.3/data/', query=new URLSearchParams(location.search), gameId=query.get('game')||'', debugEnabled=query.has('debug'), $=selector=>document.querySelector(selector);
let playtime, game, preparedContent, objectUrl, loaderScript, loadController, renderTimer, bootTimer, raf, runToken=0, coreStarted=false, mounted=false, bootRequested=false, firstFrame=false, compatibilityRetried=false, pendingMobileBoot=false, orientationLocked=false, settingsOpen=false, sampleStart, lastFrame, frames=0, dropped=0, renderedFps=0;
export const PS1_PHASES=['preparing','network_check','downloading','download_complete','core_loading','content_mounting','booting','running','error'];
export const ps1LoadState={phase:'preparing',loadedBytes:0,totalBytes:0,percent:0,speedBps:0,etaSeconds:null,currentFile:null,error:null};
const shell=$('#ps1-player-shell');
const loading=new EmulatorLoadingManager({profile:'ps1'});
const boot=new EmulatorBootDiagnostics({system:'ps1',container:'#ps1-emulator',loading,onError:error=>showError(error,false),debug:debugEnabled});
const inputManager=new EmulatorInputManager({system:'ps1',gameId,mount:$('#controls-settings')});
const viewport=new EmulatorViewportManager({shell,container:$('#ps1-emulator'),debug:query.has('debugViewport')}).start();
const isMobile=()=>matchMedia('(pointer: coarse)').matches&&(navigator.maxTouchPoints>0||'ontouchstart'in window)&&Math.min(innerWidth,innerHeight)<=900;
const capabilities={logicalProcessors:navigator.hardwareConcurrency||'indisponível',deviceMemory:navigator.deviceMemory||'indisponível',crossOriginIsolated,sharedArrayBuffer:typeof SharedArrayBuffer!=='undefined',webAssembly:typeof WebAssembly!=='undefined',webgl2:Boolean(document.createElement('canvas').getContext('webgl2'))};
const deviceProfile=(()=>{const cpu=navigator.hardwareConcurrency||4,ram=navigator.deviceMemory||4;return cpu<=4||ram<=4?'low':cpu>=8&&ram>=6?'high':'medium';})();
const saved=(()=>{try{return JSON.parse(localStorage.getItem('ps1PerformanceProfile')||'{}');}catch{return {};}})();
$('#profile').value=saved.profile||'auto';$('#frameskip').value=saved.frameskip||(deviceProfile==='high'?'0':'auto');$('#audio').value=saved.audio||(deviceProfile==='low'?'stable':'balanced');

function bootLog(message,details){if(details===undefined)console.info(`[PS1-BOOT] ${message}`);else console.info(`[PS1-BOOT] ${message}`,details);}
function safeError(error){return {code:error?.code||error?.name||'UNKNOWN',status:error?.status,message:error?.message};}
function coreOptions(compatible=$('#profile').value==='compatible') {return {pcsx_rearmed_drc:'enabled',pcsx_rearmed_neon_enhancement_enable:'disabled',pcsx_rearmed_duping_enable:'enabled',pcsx_rearmed_frameskip:compatible?'1':($('#frameskip').value==='auto'?'0':$('#frameskip').value),pcsx_rearmed_gpu_thread_rendering:'disabled',pcsx_rearmed_psxclock:'57',pcsx_rearmed_gpu_unai_blending:'enabled'};}
function persist(){localStorage.setItem('ps1PerformanceProfile',JSON.stringify({profile:$('#profile').value,frameskip:$('#frameskip').value,audio:$('#audio').value,deviceProfile}));}
function setCoreOption(key,value){try{window.EJS_emulator?.setCoreOption?.(key,value);return true;}catch{return false;}}
function diagnostics(){const canvas=$('#ps1-emulator canvas'),rows={...capabilities,isMobile:isMobile(),phase:ps1LoadState.phase,coreStarted,mounted,bootRequested,firstFrame,compatibilityRetried,emulatorThreads:false,renderedFps:renderedFps.toFixed(1),droppedFrames:dropped,internalResolution:'nativa',canvas:canvas?`${canvas.width}×${canvas.height}`:'ausente',webgl:canvas?.getContext?.('webgl')?'disponível':'não confirmado',bios:'BIOS configurada pelo loader; HLE permitido'};$('#diagnostics').innerHTML=Object.entries(rows).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');}
function measure(now){if(!sampleStart)sampleStart=now;if(lastFrame&&now-lastFrame>34)dropped+=Math.max(0,Math.round((now-lastFrame)/16.67)-1);lastFrame=now;frames++;if(now-sampleStart>=3000){renderedFps=frames*1000/(now-sampleStart);frames=0;sampleStart=now;diagnostics();autoTune();}raf=requestAnimationFrame(measure);}
function autoTune(){if($('#frameskip').value!=='auto'||!window.EJS_emulator||$('#profile').value==='compatible')return;setCoreOption('pcsx_rearmed_frameskip',renderedFps>=50?'0':renderedFps>=40?'1':renderedFps>=30?'2':'3');}
const formatBytes=value=>value>=1e9?`${(value/1e9).toFixed(2)} GB`:value>=1e6?`${(value/1e6).toFixed(1)} MB`:value>=1e3?`${(value/1e3).toFixed(1)} KB`:`${value} B`;
function renderLoadState(){renderTimer=0;const state=ps1LoadState,known=state.totalBytes>0;$('#loading-details').hidden=state.phase!=='downloading';$('#loading-bytes').textContent=known?`${formatBytes(state.loadedBytes)} / ${formatBytes(state.totalBytes)}`:`${formatBytes(state.loadedBytes)} carregados`;$('#loading-speed').textContent=state.speedBps>0?`${formatBytes(state.speedBps)}/s`:'';$('#loading-eta').textContent=state.etaSeconds!=null?`~${state.etaSeconds<60?Math.ceil(state.etaSeconds)+' s':Math.ceil(state.etaSeconds/60)+' min'} restantes`:'';$('#initializing').hidden=!['download_complete','core_loading','content_mounting','booting'].includes(state.phase);}
function updateLoad(patch,immediate=false){Object.assign(ps1LoadState,patch);if(immediate){clearTimeout(renderTimer);renderLoadState();}else if(!renderTimer)renderTimer=setTimeout(renderLoadState,150);}
function showError(error,blackScreen=false,token=runToken){if(token!==runToken||error?.name==='AbortError')return;clearTimeout(bootTimer);updateLoad({phase:'error',error:safeError(error)},true);$('#loading').hidden=true;$('#error').hidden=false;$('#error p').textContent=blackScreen?'O jogo foi carregado, mas não iniciou corretamente neste dispositivo.':error.message||String(error);bootLog(error.code||'BOOT_FAILED',safeError(error));}

function noteFrame(){if(!bootRequested||firstFrame)return;const canvas=$('#ps1-emulator canvas');if(!canvas||!canvas.width||!canvas.height)return;firstFrame=true;playtime?.start();playtime?.markRunning();bindEmulatorControls(window.EJS_emulator,playtime);viewport.setNativeSize(canvas.width,canvas.height);viewport.fit();clearTimeout(bootTimer);boot.running();bootLog('first frame');loading.markFirstFrame();updateLoad({phase:'running'},true);setTimeout(()=>{$('#loading').hidden=true;},300);$('#fullscreen-prompt').hidden=true;raf=requestAnimationFrame(measure);setTimeout(autoTune,10000);}
function instrumentFrames(){const wrap=(prototype,name)=>{if(!prototype||prototype[name]?.__ps1Wrapped)return;const original=prototype[name];function wrapped(...args){const result=original.apply(this,args);if(this.canvas?.closest?.('#ps1-emulator'))queueMicrotask(noteFrame);return result;}wrapped.__ps1Wrapped=true;prototype[name]=wrapped;};for(const proto of [window.WebGLRenderingContext?.prototype,window.WebGL2RenderingContext?.prototype])for(const method of ['drawArrays','drawElements'])wrap(proto,method);for(const method of ['drawImage','putImageData','fillRect'])wrap(window.CanvasRenderingContext2D?.prototype,method);}
instrumentFrames();

async function requestPlayerFullscreen(userInitiated=false){if(!userInitiated&&!isMobile()&&document.fullscreenElement!==shell)return false;try{if(document.fullscreenElement!==shell)await shell.requestFullscreen();if(screen.orientation?.lock&&isMobile()){try{await screen.orientation.lock('landscape');orientationLocked=true;}catch{}}return document.fullscreenElement===shell;}catch(error){bootLog('fullscreen blocked',{name:error?.name});return false;}}
async function mobileGateThenBoot(){if(!isMobile()){requestBoot();return;}if(await requestPlayerFullscreen()){requestBoot();return;}pendingMobileBoot=true;$('#fullscreen-prompt').hidden=false;$('#fullscreen-prompt').focus();}
function requestBoot(){if(bootRequested)return;pendingMobileBoot=false;$('#fullscreen-prompt').hidden=true;bootRequested=true;loading.completeStep('boot_requested').completeStep('waiting_first_frame');boot.waitingFirstFrame();updateLoad({phase:'booting'},true);bootLog('boot requested');try{window.EJS_emulator?.play?.();}catch{}bootTimer=setTimeout(()=>handleBlackScreen(),20000);}
async function handleBlackScreen(){if(firstFrame)return;const canvas=$('#ps1-emulator canvas');const code=!canvas?'NO_FIRST_FRAME':capabilities.webgl2||canvas.getContext?.('webgl')?'BLACK_SCREEN_TIMEOUT':'WEBGL_CONTEXT_FAILED';bootLog(code,{canvas:Boolean(canvas),coreStarted,mounted});if(!compatibilityRetried&&preparedContent){compatibilityRetried=true;bootLog('automatic compatible retry');await launchEmulator(runToken,true);return;}showError(Object.assign(new Error('O jogo foi carregado, mas não iniciou corretamente neste dispositivo.'),{code}),true);}
function destroyEmulator({keepContent=true}={}){boot.destroy();clearTimeout(bootTimer);cancelAnimationFrame(raf);loaderScript?.remove();loaderScript=null;try{window.EJS_emulator?.stop?.();window.EJS_emulator?.destroy?.();}catch{}delete window.EJS_emulator;$('#ps1-emulator').replaceChildren();coreStarted=mounted=bootRequested=firstFrame=pendingMobileBoot=false;if(!keepContent&&objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;preparedContent=null;}}
async function launchEmulator(token,compatible=false){if(token!==runToken)return;destroyEmulator({keepContent:true});$('#loading').hidden=false;$('#error').hidden=true;loading.completeStep('runtime_available').setPhase('loading_runtime').startTimeout('loader_loaded',20000,'Etapa: Runtime');updateLoad({phase:'core_loading'},true);Object.assign(window,{EJS_player:'#ps1-emulator',EJS_core:'psx',EJS_gameUrl:objectUrl,EJS_pathtodata:DATA,EJS_startOnLoaded:true,EJS_gameName:resolvePs1Launch(game).dependencies.length?`${game.name}.zip`:game.name,EJS_threads:false,EJS_gameOptions:coreOptions(compatible),EJS_VirtualGamepadSettings:{}});if(compatible){window.EJS_webgl=false;window.EJS_threads=false;$('#profile').value='compatible';}else delete window.EJS_webgl;
  window.EJS_onGameStart=()=>{if(token!==runToken)return;clearTimeout(bootTimer);coreStarted=true;mounted=true;boot.mounted();bootLog('content mounted');if(isMobile()){try{window.EJS_emulator?.pause?.();}catch{}}mobileGateThenBoot();};
  window.EJS_onAudioStart=()=>bootLog('audio started');
  loaderScript=document.createElement('script');loaderScript.src=`${DATA}loader.js`;loaderScript.onload=()=>{if(token!==runToken)return;loading.clearTimeout();loading.completeStep('loader_loaded');boot.watchRuntime({current:()=>token===runToken,onCore:()=>{coreStarted=true;bootLog('core ready');},onCanvas:canvas=>{loading.completeStep('input_ready');viewport.setNativeSize(canvas.width,canvas.height);updateLoad({phase:'content_mounting'},true);}});};loaderScript.onerror=()=>showError(Object.assign(new Error('Falha ao carregar o runtime do EmulatorJS. Etapa: Runtime'),{code:'runtime_loading'}),false,token);document.head.append(loaderScript);
}
async function start(){const token=++runToken;loadController?.abort();loadController=new AbortController();destroyEmulator({keepContent:false});compatibilityRetried=false;loading.reset();Object.assign(ps1LoadState,{phase:'preparing',loadedBytes:0,totalBytes:0,percent:0,speedBps:0,etaSeconds:null,currentFile:null,error:null});$('#error').hidden=true;$('#loading').hidden=false;$('#cancel').hidden=false;renderLoadState();try{const resolved=await fetchPs1Game(gameId,{fetchImpl:(url,init={})=>fetch(url,{...init,signal:loadController.signal})});game=resolved.game;if(!playtime)playtime=new PlaytimeTracker(descriptor({system:'ps1',id:game.id||gameId,title:game.name,cover:game.cover}));$('#game-name').textContent=game.name;$('#loading-game').textContent=game.name;document.title=`${game.name} — PlumpGames`;bootLog('bootKey',{format:game.format,file:(game.bootKey||game.key).split('/').pop()});loading.setPhase('network');updateLoad({phase:'network_check'},true);const began=performance.now();preparedContent=await downloadPs1Content(game,{signal:loadController.signal,onMetadata:({totalBytes})=>updateLoad({phase:'downloading',totalBytes:totalBytes||0},true),onRetry:({error,attempt})=>bootLog(error.code||'NETWORK_RETRY',{attempt}),onProgress:({loadedBytes,totalBytes,currentFile})=>{const elapsed=(performance.now()-began)/1000,speedBps=elapsed>.25?loadedBytes/elapsed:0,percent=totalBytes?Math.min(100,Math.floor(loadedBytes/totalBytes*100)):0;loading.setDownloadProgress(percent);updateLoad({phase:'downloading',loadedBytes,totalBytes:totalBytes||0,percent,speedBps,etaSeconds:totalBytes&&speedBps?(totalBytes-loadedBytes)/speedBps:null,currentFile});}});if(token!==runToken)return;objectUrl=preparedContent.gameUrl;loading.setDownloadProgress(100);updateLoad({phase:'download_complete',loadedBytes:preparedContent.totalBytes,totalBytes:preparedContent.totalBytes,percent:100,etaSeconds:0},true);bootLog('download complete');await launchEmulator(token,false);}catch(error){showError(error,false,token);}}
function leavePlayer(){loadController?.abort();++runToken;destroyEmulator({keepContent:false});if(window.opener&&!window.opener.closed){window.opener.focus();window.close();setTimeout(()=>{location.href='/Emuladores/PS1/';},250);}else location.href='/Emuladores/PS1/';}
function toggleSettings(force){settingsOpen=force??!settingsOpen;if(!settingsOpen)inputManager.close();$('#settings').hidden=!settingsOpen;$('#settings-backdrop').hidden=!settingsOpen;$('#settings-toggle').setAttribute('aria-expanded',String(settingsOpen));if(settingsOpen)diagnostics();}
$('#settings-toggle').onclick=()=>toggleSettings();$('#settings-close').onclick=()=>toggleSettings(false);$('#settings-backdrop').onclick=()=>toggleSettings(false);$('#diagnostics-toggle').onclick=()=>{$('#diagnostics').hidden=!$('#diagnostics').hidden;diagnostics();};$('#diagnostics').hidden=!debugEnabled;
$('#details-toggle').checked=localStorage.getItem('emulatorLoadingDetails')==='1';$('#initialization-details').hidden=!$('#details-toggle').checked;$('#details-toggle').onchange=event=>{localStorage.setItem('emulatorLoadingDetails',event.target.checked?'1':'0');$('#initialization-details').hidden=!event.target.checked;loading.render();};
$('#fullscreen').onclick=()=>requestPlayerFullscreen(true);$('#fullscreen-prompt').onclick=async()=>{await requestPlayerFullscreen(true);requestBoot();};$('#retry').onclick=start;$('#compatibility').onclick=()=>{compatibilityRetried=true;launchEmulator(runToken,true);};$('#restart').onclick=start;$('#cancel').onclick=leavePlayer;$('#error-back').onclick=leavePlayer;$('#back').onclick=event=>{event.preventDefault();leavePlayer();};
for(const id of ['profile','frameskip','audio'])$(`#${id}`).onchange=()=>{persist();if(id!=='audio')for(const [key,value]of Object.entries(coreOptions()))setCoreOption(key,value);};
document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement!==shell){if(orientationLocked)screen.orientation?.unlock?.();orientationLocked=false;shell.classList.remove('is-fullscreen');}else shell.classList.add('is-fullscreen');});document.addEventListener('fullscreenerror',event=>bootLog('fullscreenerror',{type:event.type}));addEventListener('resize',diagnostics,{passive:true});addEventListener('orientationchange',diagnostics,{passive:true});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&settingsOpen&&!inputManager.captureId){event.preventDefault();event.stopPropagation();toggleSettings(false);}},true);document.addEventListener('visibilitychange',()=>{try{if(document.hidden){window.EJS_emulator?.pause?.();playtime?.markPaused();}else if(bootRequested){window.EJS_emulator?.play?.();if(firstFrame)playtime?.markRunning();}}catch{}});addEventListener('pagehide',()=>{inputManager.destroy();viewport.destroy();loadController?.abort();++runToken;destroyEmulator({keepContent:false});});
start();
